package org.shev4ik.interview.advanced_fp.level3_theory

/**
 * AdvFP028 - Profunctor
 *
 * A Profunctor is contravariant in the first argument and covariant in the second.
 * dimap: P[A, B] => (C => A) => (B => D) => P[C, D]
 * Strong profunctors have first/second, Choice profunctors have left/right.
 * These form the basis of profunctor optics.
 */
object AdvFP028_Profunctor {

  // ============================================================
  // Exercise 1: Define the Profunctor typeclass
  // ============================================================
  trait Profunctor[P[_, _]] {
    def dimap[A, B, C, D](pab: P[A, B])(f: C => A)(g: B => D): P[C, D]
    def lmap[A, B, C](pab: P[A, B])(f: C => A): P[C, B] = dimap(pab)(f)(identity)
    def rmap[A, B, D](pab: P[A, B])(g: B => D): P[A, D] = dimap(pab)(identity[A])(g)
  }

  // TODO: Implement Profunctor for Function1
  implicit val function1Profunctor: Profunctor[Function1] = ???

  // ============================================================
  // Exercise 2: Define the Strong profunctor (Cartesian)
  // Strong adds: first: P[A, B] => P[(A, C), (B, C)]
  // ============================================================
  trait Strong[P[_, _]] extends Profunctor[P] {
    def first[A, B, C](pab: P[A, B]): P[(A, C), (B, C)]
    def second[A, B, C](pab: P[A, B]): P[(C, A), (C, B)]
  }

  // TODO: Implement Strong for Function1
  implicit val function1Strong: Strong[Function1] = ???

  // ============================================================
  // Exercise 3: Define the Choice profunctor (Cocartesian)
  // Choice adds: left: P[A, B] => P[Either[A, C], Either[B, C]]
  // ============================================================
  trait Choice[P[_, _]] extends Profunctor[P] {
    def left[A, B, C](pab: P[A, B]): P[Either[A, C], Either[B, C]]
    def right[A, B, C](pab: P[A, B]): P[Either[C, A], Either[C, B]]
  }

  // TODO: Implement Choice for Function1
  implicit val function1Choice: Choice[Function1] = ???

  // ============================================================
  // Exercise 4: Implement the Star profunctor
  // Star[F, A, B] = A => F[B] (Kleisli arrow)
  // It is a profunctor when F is a functor.
  // ============================================================
  case class Star[F[_], A, B](run: A => F[B])

  trait Functor[F[_]] {
    def map[A, B](fa: F[A])(f: A => B): F[B]
  }

  // TODO: Implement Profunctor for Star[F, *, *]
  def starProfunctor[F[_]: Functor]: Profunctor[({type L[A, B] = Star[F, A, B]})#L] = ???

  // ============================================================
  // Exercise 5: Implement the Forget profunctor
  // Forget[R, A, B] = A => R (ignores B, extracts R from A)
  // This is used to implement getters in profunctor optics.
  // ============================================================
  case class Forget[R, A, B](run: A => R)

  // TODO: Implement Profunctor for Forget[R, *, *]
  def forgetProfunctor[R]: Profunctor[({type L[A, B] = Forget[R, A, B]})#L] = ???

  // ============================================================
  // Exercise 6: Implement Strong for Star when F is Applicative-like
  // We'll use a simpler version: Strong for Star[F, *, *] when F is a Functor
  // first sends (A, C) to F[(B, C)] by running A => F[B] and pairing with C.
  // ============================================================
  trait Applicative[F[_]] extends Functor[F] {
    def pure[A](a: A): F[A]
    def ap[A, B](ff: F[A => B])(fa: F[A]): F[B]
  }

  // TODO: Implement Strong for Star[F, *, *] when F has Functor
  def starStrong[F[_]](implicit F: Functor[F]): Strong[({type L[A, B] = Star[F, A, B]})#L] = ???

  // ============================================================
  // Exercise 7: Demonstrate profunctor composition
  // Given P[A, B] and Q[B, C], compose into a new profunctor Procompose[P, Q, A, C].
  // ============================================================
  trait Procompose[P[_, _], Q[_, _], A, C] {
    type B
    val first: P[A, B]
    val second: Q[B, C]
  }

  // TODO: Create a Procompose instance
  def procompose[P[_, _], Q[_, _], A, B0, C](p: P[A, B0], q: Q[B0, C]): Procompose[P, Q, A, C] = ???

  // ============================================================
  // Exercise 8: Implement the Tambara module
  // Tambara[P, A, B] = forall C. P[(A, C), (B, C)]
  // This is the free Strong profunctor generated by P.
  // We'll implement a simplified version.
  // ============================================================
  trait Tambara[P[_, _], A, B] {
    def run[C]: P[(A, C), (B, C)]
  }

  // TODO: Convert a Strong profunctor value into Tambara
  def toTambara[P[_, _], A, B](pab: P[A, B])(implicit S: Strong[P]): Tambara[P, A, B] = ???

  // TODO: Extract from Tambara back to a profunctor value
  def fromTambara[P[_, _], A, B](t: Tambara[P, A, B]): P[(A, Unit), (B, Unit)] = ???

  def main(args: Array[String]): Unit = {
    // Exercise 1: Profunctor for Function1
    val inc: Int => Int = _ + 1
    val dimapped = function1Profunctor.dimap(inc)((s: String) => s.length)(_ * 10)
    assert(dimapped("hello") == 60) // length("hello")=5, +1=6, *10=60
    println("Exercise 1 passed: Profunctor for Function1")

    // Exercise 2: Strong for Function1
    val firsted = function1Strong.first[Int, Int, String](inc)
    assert(firsted((5, "hi")) == (6, "hi"))
    val seconded = function1Strong.second[Int, Int, String](inc)
    assert(seconded(("hi", 5)) == ("hi", 6))
    println("Exercise 2 passed: Strong for Function1")

    // Exercise 3: Choice for Function1
    val lefted = function1Choice.left[Int, Int, String](inc)
    assert(lefted(Left(5)) == Left(6))
    assert(lefted(Right("hi")) == Right("hi"))
    println("Exercise 3 passed: Choice for Function1")

    // Exercise 4: Star profunctor
    implicit val optionFunctor: Functor[Option] = new Functor[Option] {
      def map[A, B](fa: Option[A])(f: A => B): Option[B] = fa.map(f)
    }
    val sp = starProfunctor[Option]
    val star = Star[Option, Int, String](n => Some(n.toString))
    val dimappedStar = sp.dimap(star)((s: String) => s.length)("Result: " + _)
    assert(dimappedStar.run("hello") == Some("Result: 5"))
    println("Exercise 4 passed: Star profunctor")

    // Exercise 5: Forget profunctor
    val fp = forgetProfunctor[Int]
    val forget = Forget[Int, String, Boolean](_.length)
    val dimappedForget = fp.dimap(forget)((n: Int) => n.toString)(identity)
    assert(dimappedForget.run(42) == 2) // "42".length
    println("Exercise 5 passed: Forget profunctor")

    // Exercise 6: Strong for Star
    val ss = starStrong[Option]
    val starInc = Star[Option, Int, Int](n => Some(n + 1))
    val firstedStar = ss.first[Int, Int, String](starInc)
    assert(firstedStar.run((5, "hi")) == Some((6, "hi")))
    println("Exercise 6 passed: Strong for Star")

    // Exercise 7: Procompose
    val pc = procompose[Function1, Function1, String, Int, Boolean](
      (s: String) => s.length,
      (n: Int) => n > 3
    )
    println("Exercise 7 passed: Procompose")

    // Exercise 8: Tambara
    val tamb = toTambara[Function1, Int, Int](inc)
    val result = tamb.run[String]((5, "ctx"))
    assert(result == (6, "ctx"))
    val extracted = fromTambara[Function1, Int, Int](tamb)
    assert(extracted((5, ())) == (6, ()))
    println("Exercise 8 passed: Tambara module")

    println("\nAll exercises passed!")
  }
}
