package org.shev4ik.interview.logic_intellect.level1_foundations

/**
 * =Number Sequences and Patterns=
 *
 * ==Theory: Look-and-Say Sequence==
 *
 * The '''look-and-say sequence''' (Morris number sequence, OEIS A005150) is generated by
 * reading off the digits of the previous term:
 * {{{
 * 1           -> "one 1"       -> 11
 * 11          -> "two 1s"      -> 21
 * 21          -> "one 2, one 1" -> 1211
 * 1211        -> "one 1, one 2, two 1s" -> 111221
 * }}}
 *
 * Properties:
 *  - The sequence grows roughly by a factor of Conway's constant (~1.303577...) per term.
 *  - No digit greater than 3 ever appears (proved by John Conway).
 *  - Related to Conway's cosmological theorem about "elements" in the sequence.
 *
 * ==Theory: Collatz Conjecture (3n+1 Problem)==
 *
 * Starting from any positive integer n, repeatedly apply:
 *  - If n is even: n = n / 2
 *  - If n is odd: n = 3n + 1
 *
 * '''Conjecture:''' the sequence always eventually reaches 1.
 *
 * This is one of the most famous unsolved problems in mathematics. It has been verified
 * for all starting values up to approximately 2^68, but no proof exists.
 *
 * Key observations:
 *  - The sequence can grow dramatically before descending (e.g., starting at 27 reaches 9232).
 *  - '''Stopping time:''' number of steps to reach 1 for the first time.
 *  - Average stopping time grows logarithmically, but individual sequences are unpredictable.
 *  - Relevant to CS: demonstrates that simple rules can produce complex, hard-to-analyze behavior.
 *
 * ==Theory: Kaprekar Routine==
 *
 * For a 4-digit number (not all digits the same):
 *  1. Arrange digits in descending order to form the largest number.
 *  2. Arrange digits in ascending order to form the smallest number.
 *  3. Subtract smallest from largest.
 *  4. Repeat with the result.
 *
 * '''Kaprekar's constant:''' the process always converges to '''6174''' within 7 iterations
 * (for 4-digit numbers with not all digits identical).
 *
 * ==Theory: Van Eck Sequence==
 *
 * Start with a(0) = 0. For each subsequent term:
 *  - If the previous term has NOT appeared before in the sequence: a(n) = 0.
 *  - If the previous term HAS appeared before: a(n) = distance to its most recent prior occurrence.
 *
 * {{{
 * 0, 0, 1, 0, 2, 0, 2, 2, 1, 6, 0, 5, 0, 2, ...
 * }}}
 *
 * Properties: conjectured that every non-negative integer appears infinitely often,
 * but this is unproven.
 *
 * ==Comparison: Termination Analysis==
 *
 *  - '''Look-and-say:''' always terminates per step (finite string operations), infinite sequence.
 *  - '''Collatz:''' termination (reaching 1) is conjectured but unproven -- a major open problem.
 *  - '''Kaprekar:''' proven to terminate in at most 7 steps for valid 4-digit inputs.
 *  - '''Happy numbers:''' always terminate because the sequence is bounded and must cycle.
 *  - '''Digital root:''' always terminates because the value strictly decreases (for n >= 10).
 *
 * ==Interview Tips==
 *
 *  - Pattern recognition questions test your ability to simulate a process, spot cycles, and
 *    reason about convergence.
 *  - For look-and-say: practice run-length encoding (a common string manipulation technique).
 *  - For Collatz: be aware of potential overflow with Long vs Int for large starting values.
 *  - For cycle detection (happy numbers): use Floyd's tortoise-and-hare or a HashSet.
 *  - Digital root has a direct formula: dr(n) = 1 + (n-1) % 9 for n > 0. Know both the
 *    iterative and formula approaches.
 *  - Recaman's sequence tests set membership tracking -- use a HashSet for O(1) lookups.
 */
object Logic003_NumberPatterns {

  // Exercise 1: Generate the nth term (1-indexed) of the look-and-say sequence.
  // Term 1 = "1", Term 2 = "11", Term 3 = "21", Term 4 = "1211", Term 5 = "111221"
  // Use run-length encoding on the previous term to generate the next.
  def exercise1_lookAndSay(n: Int): String = ???

  // Exercise 2: Return the number of steps for the Collatz sequence starting at n to reach 1.
  // If even: n/2. If odd: 3n+1. Count each application as one step.
  // Example: 6 -> 3 -> 10 -> 5 -> 16 -> 8 -> 4 -> 2 -> 1 => 8 steps
  def exercise2_collatzLength(n: Long): Int = ???

  // Exercise 3: Return the full Collatz sequence as a List[Long], starting from n and ending at 1.
  // Example: exercise3_collatzSequence(6) => List(6, 3, 10, 5, 16, 8, 4, 2, 1)
  def exercise3_collatzSequence(n: Long): List[Long] = ???

  // Exercise 4: Apply the Kaprekar routine to a 4-digit number.
  // Pad with leading zeros if necessary (e.g., 0001).
  // Sort digits descending - sort ascending, repeat until reaching 6174 or 0.
  // Return the number of steps. If input has all identical digits, return 0.
  // Example: 3524 -> 5432-2345=3087 -> 8730-0378=8352 -> 8532-2358=6174 => 3 steps
  def exercise4_kaprekar(num: Int): Int = ???

  // Exercise 5: Generate the first n terms of the Van Eck sequence.
  // a(0) = 0. For a(n): if a(n-1) has not appeared before in a(0..n-2), then a(n) = 0.
  // Otherwise, a(n) = n - 1 - (last index where a(n-1) appeared before position n-1).
  // Example: first 10 terms: List(0, 0, 1, 0, 2, 0, 2, 2, 1, 6)
  def exercise5_vanEck(n: Int): List[Int] = ???

  // Exercise 6: Check if a number is a "happy number."
  // Repeatedly replace the number by the sum of the squares of its digits.
  // If the process reaches 1, the number is happy. Otherwise it loops forever.
  // Example: 19 -> 1+81=82 -> 64+4=68 -> 36+64=100 -> 1 => true
  // Example: 2 -> 4 -> 16 -> 37 -> 58 -> 89 -> 145 -> 42 -> 20 -> 4 (cycle) => false
  def exercise6_happyNumber(n: Int): Boolean = ???

  // Exercise 7: Compute the digital root of a positive integer.
  // Repeatedly sum the digits until a single digit remains.
  // Example: 9875 -> 9+8+7+5=29 -> 2+9=11 -> 1+1=2 => 2
  // Formula shortcut: dr(n) = 1 + (n - 1) % 9 for n > 0, dr(0) = 0
  def exercise7_digitalRoot(n: Int): Int = ???

  // Exercise 8: Generate the first n terms of Recaman's sequence.
  // a(0) = 0. For n >= 1:
  //   If a(n-1) - n > 0 AND (a(n-1) - n) has not appeared in the sequence yet:
  //     a(n) = a(n-1) - n
  //   Else:
  //     a(n) = a(n-1) + n
  // Example: first 10 terms: List(0, 1, 3, 6, 2, 7, 13, 20, 12, 21)
  def exercise8_recamanSequence(n: Int): List[Int] = ???

  def main(args: Array[String]): Unit = {
    // Exercise 1: lookAndSay
    assert(exercise1_lookAndSay(1) == "1")
    assert(exercise1_lookAndSay(2) == "11")
    assert(exercise1_lookAndSay(3) == "21")
    assert(exercise1_lookAndSay(4) == "1211")
    assert(exercise1_lookAndSay(5) == "111221")
    println("Exercise 1 passed: exercise1_lookAndSay")

    // Exercise 2: collatzLength
    assert(exercise2_collatzLength(1) == 0)
    assert(exercise2_collatzLength(6) == 8)
    assert(exercise2_collatzLength(27) == 111)
    println("Exercise 2 passed: exercise2_collatzLength")

    // Exercise 3: collatzSequence
    assert(exercise3_collatzSequence(6) == List(6, 3, 10, 5, 16, 8, 4, 2, 1))
    assert(exercise3_collatzSequence(1) == List(1))
    println("Exercise 3 passed: exercise3_collatzSequence")

    // Exercise 4: kaprekar
    assert(exercise4_kaprekar(3524) == 3)
    assert(exercise4_kaprekar(6174) == 0)
    assert(exercise4_kaprekar(1111) == 0)
    assert(exercise4_kaprekar(1000) == 5)
    println("Exercise 4 passed: exercise4_kaprekar")

    // Exercise 5: vanEck
    assert(exercise5_vanEck(1) == List(0))
    assert(exercise5_vanEck(10) == List(0, 0, 1, 0, 2, 0, 2, 2, 1, 6))
    println("Exercise 5 passed: exercise5_vanEck")

    // Exercise 6: happyNumber
    assert(exercise6_happyNumber(19) == true)
    assert(exercise6_happyNumber(1) == true)
    assert(exercise6_happyNumber(2) == false)
    assert(exercise6_happyNumber(7) == true)
    println("Exercise 6 passed: exercise6_happyNumber")

    // Exercise 7: digitalRoot
    assert(exercise7_digitalRoot(0) == 0)
    assert(exercise7_digitalRoot(9875) == 2)
    assert(exercise7_digitalRoot(9) == 9)
    assert(exercise7_digitalRoot(123) == 6)
    println("Exercise 7 passed: exercise7_digitalRoot")

    // Exercise 8: recamanSequence
    assert(exercise8_recamanSequence(1) == List(0))
    assert(exercise8_recamanSequence(10) == List(0, 1, 3, 6, 2, 7, 13, 20, 12, 21))
    println("Exercise 8 passed: exercise8_recamanSequence")

    println("\nAll exercises passed!")
  }
}
