import { Question } from '@/types/question';

const questions: Question[] = [
  {
    id: 'scala-db-l4-001',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'In Slick, what is the actual SQL generated by `users.filter(_.name.like("%Alice%")).map(_.email).result`?',
    options: [
      'SELECT "email" FROM "users" WHERE "name" LIKE \'%Alice%\'',
      'SELECT email FROM users WHERE name CONTAINS \'Alice\'',
      'SELECT email FROM users WHERE MATCH(name) AGAINST (\'Alice\')',
      'SELECT email FROM users WHERE name ILIKE \'%Alice%\'',
    ],
    correctAnswer: 0,
    explanation: 'Slick\'s `.like` generates a SQL LIKE clause. The .map(_.email) becomes a SELECT projection. Column and table names are quoted per the profile\'s naming convention.',
    codeSnippet: `val q = users.filter(_.name.like("%Alice%")).map(_.email).result
// Generated: SELECT "email" FROM "users" WHERE "name" LIKE '%Alice%'`,
    tags: ['slick', 'sql-generation', 'like', 'internals'],
  },
  {
    id: 'scala-db-l4-002',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'What is a potential issue with using `Slick.stream` without `withPinnedSession` for PostgreSQL streaming?',
    options: [
      'Without pinned session, Slick may switch connections between stream chunks, breaking the server-side cursor that requires a single connection',
      'Without pinned session, Slick uses autocommit which closes cursors after each row',
      'Without pinned session, stream results are returned in random order',
      'There is no issue — withPinnedSession is optional for streaming',
    ],
    correctAnswer: 0,
    explanation: 'Server-side cursors in PostgreSQL are tied to a specific connection and transaction. If Slick acquires different connections for different stream chunks, the cursor will be unavailable on the second connection.',
    tags: ['slick', 'streaming', 'pinned-session', 'cursor', 'postgresql'],
  },
  {
    id: 'scala-db-l4-003',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'In Slick, what is the difference between `forceInsert` and the regular `+=` insert?',
    options: [
      'forceInsert includes auto-increment columns in the INSERT statement; += excludes them and lets the database generate them',
      'forceInsert bypasses foreign key constraints; += enforces them',
      'forceInsert is transactional; += is not',
      'forceInsert returns the inserted row; += returns only the count',
    ],
    correctAnswer: 0,
    explanation: '`forceInsert` includes all columns (including AutoInc ones) in the INSERT, allowing you to specify the ID explicitly. Regular `+=` excludes AutoInc columns so the database generates them.',
    codeSnippet: `// Regular insert — database generates id:
users += User(0, "Alice")

// Force insert — explicitly set id=42:
users.forceInsert(User(42, "Alice"))`,
    tags: ['slick', 'force-insert', 'auto-increment', 'internals'],
  },
  {
    id: 'scala-db-l4-004',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'What is the `ExecutionContext` that Slick uses internally for `Future` composition, and why does it matter?',
    options: [
      'Slick uses its own ExecutionContext for database operations, but you can override it; using the global ExecutionContext for blocking JDBC can cause thread starvation',
      'Slick always uses Scala\'s global ExecutionContext',
      'Slick uses a single-threaded ExecutionContext for all operations to preserve ordering',
      'The ExecutionContext is set once per Database instance and cannot be changed',
    ],
    correctAnswer: 0,
    explanation: 'Slick\'s Database can be configured with a custom ExecutionContext. The default creates a thread pool sized to the connection pool. Sharing the global context risks thread starvation from blocking JDBC calls.',
    codeSnippet: `// Custom executor:
val db = Database.forURL(url,
  executor = AsyncExecutor("custom", numThreads = 10, queueSize = 1000)
)`,
    tags: ['slick', 'execution-context', 'thread-pool', 'performance'],
  },
  {
    id: 'scala-db-l4-005',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Doobie',
    question: 'In Doobie, what is the behavior when a `ConnectionIO` raises an exception inside `.transact(xa)` after some operations have already executed?',
    options: [
      'Doobie catches the exception, rolls back the entire transaction (including previously executed operations in this transact call), and re-raises the exception in IO',
      'Operations already executed are committed; only subsequent operations are rolled back',
      'The exception is swallowed and a default value is returned',
      'Doobie retries the failed operation up to 3 times before rolling back',
    ],
    correctAnswer: 0,
    explanation: 'Doobie\'s .transact wraps the entire ConnectionIO in BEGIN/COMMIT/ROLLBACK. Any exception triggers a full ROLLBACK of all operations in that transaction, then the exception propagates in IO.',
    tags: ['doobie', 'transactions', 'rollback', 'error-handling', 'transact'],
  },
  {
    id: 'scala-db-l4-006',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Doobie',
    question: 'What is the subtle issue with mixing `.transact(xa)` and `IO.sleep` inside the same for-comprehension?',
    options: [
      'IO.sleep releases the thread and the connection is returned to the pool, but the transaction may still be open — a conceptual mismatch',
      'There is no issue; IO.sleep is safely composable with ConnectionIO via transact',
      'IO.sleep inside transact causes a deadlock because it holds the connection',
      'IO.sleep cannot be used inside a transact block as it causes a compile error',
    ],
    correctAnswer: 0,
    explanation: 'If you compose IO.sleep inside a transaction via transact, the JDBC connection is held for the sleep duration. This blocks connection pool slots unnecessarily. The solution is to move IO.sleep outside the transact call.',
    codeSnippet: `// BAD — holds connection during sleep:
(for {
  r <- query.transact(xa)
  _ <- IO.sleep(5.seconds)  // wastes a connection slot
} yield r)

// GOOD:
for {
  r <- query.transact(xa)
  _ <- IO.sleep(5.seconds)  // connection already returned
} yield r`,
    tags: ['doobie', 'transactions', 'connection-leak', 'io-sleep', 'anti-pattern'],
  },
  {
    id: 'scala-db-l4-007',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Doobie',
    question: 'What is the difference between `HC.rollback` and raising an error in Doobie within a transaction?',
    options: [
      'HC.rollback explicitly rolls back without raising an error, allowing the program to continue; raising an error causes rollback AND propagates the exception',
      'HC.rollback commits prior work and starts a new transaction; raising an error has no commit',
      'Both are equivalent — Doobie handles them identically',
      'HC.rollback can only roll back to a savepoint; raising an error rolls back the entire transaction',
    ],
    correctAnswer: 0,
    explanation: 'HC.rollback issues a ROLLBACK command but the ConnectionIO continues normally (the for-comprehension proceeds). Raising an error via MonadError causes Doobie\'s transact to ROLLBACK and propagate the exception in IO.',
    codeSnippet: `// Explicit rollback without error:
val prog1 = sql"INSERT ...".update.run >> HC.rollback >> FC.pure(None)

// Rollback via error:
val prog2 = sql"INSERT ...".update.run >>
  MonadError[ConnectionIO, Throwable].raiseError(new Exception("abort"))`,
    tags: ['doobie', 'hc', 'rollback', 'error-handling', 'internals'],
  },
  {
    id: 'scala-db-l4-008',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Doobie',
    question: 'In Doobie, what is the purpose of `Transactor.Strategy` and how does it customize transaction behavior?',
    options: [
      'Strategy defines the before/after hooks for connection acquisition, transaction begin, commit, rollback, and connection return',
      'Strategy selects between optimistic and pessimistic locking for transactions',
      'Strategy configures the connection pool strategy (FIFO, LIFO, random)',
      'Strategy defines the SQL dialect and type mapping strategy for the Transactor',
    ],
    correctAnswer: 0,
    explanation: 'Transactor.Strategy is a set of ConnectionIO programs run at lifecycle points: before (setup), after (cleanup), oops (error cleanup), always (finally). You can customize auto-commit behavior, isolation level, etc.',
    codeSnippet: `val strategy = Transactor.Strategy.default.copy(
  before = HC.setAutoCommit(false) >> HC.setTransactionIsolation(TRANSACTION_SERIALIZABLE),
  after  = HC.commit,
  oops   = HC.rollback,
  always = FC.unit
)`,
    tags: ['doobie', 'transactor', 'strategy', 'transactions', 'internals'],
  },
  {
    id: 'scala-db-l4-009',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'connection pooling',
    question: 'What is the "thundering herd" problem in connection pools after a database outage, and how does HikariCP mitigate it?',
    options: [
      'After recovery, all application instances simultaneously try to establish connections, overwhelming the DB; HikariCP uses connection attempt jitter/backoff to spread reconnection attempts',
      'Too many threads simultaneously request connections, deadlocking the pool; HikariCP uses a fair queue',
      'A burst of queries after idle periods overwhelms the DB; HikariCP pre-warms connections',
      'Multiple pools compete for the same connection; HikariCP uses connection partitioning',
    ],
    correctAnswer: 0,
    explanation: 'When a database recovers from outage, all application instances rush to reconnect. HikariCP\'s initialization timeout and backoff help, but external circuit breakers and connection retry limits are also needed.',
    tags: ['connection-pooling', 'hikaricp', 'thundering-herd', 'resilience'],
  },
  {
    id: 'scala-db-l4-010',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'connection pooling',
    question: 'What is the correct thread pool configuration for Doobie in a Cats Effect 3 application?',
    options: [
      'Use IO.blocking{} for JDBC calls which automatically shifts to Cats Effect\'s built-in blocking pool, no explicit thread pool configuration needed',
      'Create a fixed thread pool with executionContext and pass it to HikariTransactor',
      'Use the default IO thread pool for all JDBC calls',
      'Create a separate CachedThreadPool for JDBC and attach it to the Transactor',
    ],
    correctAnswer: 0,
    explanation: 'In Cats Effect 3, IO.blocking{} automatically shifts work to the built-in blocking thread pool. Doobie 1.x uses this internally, so you don\'t need to manually configure a blocking ExecutionContext.',
    codeSnippet: `// Doobie 1.x with CE3 — no explicit blocking EC needed:
HikariTransactor.newHikariTransactor[IO](
  driverClassName, url, user, password,
  // No connectEC parameter in CE3 version!
)`,
    tags: ['doobie', 'cats-effect-3', 'thread-pool', 'io-blocking'],
  },
  {
    id: 'scala-db-l4-011',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Skunk',
    question: 'What is the PostgreSQL "extended query protocol" that Skunk uses, and how does it differ from the "simple query protocol"?',
    options: [
      'Extended protocol separates parse, bind, describe, and execute phases, enabling prepared statements and binary encoding; simple protocol sends SQL as raw text in one message',
      'Extended protocol supports multiple queries per message; simple protocol is single-query only',
      'Extended protocol uses binary format for all data; simple protocol uses text format',
      'Extended protocol supports transactions; simple protocol is always autocommit',
    ],
    correctAnswer: 0,
    explanation: 'PostgreSQL\'s extended query protocol (Parse/Bind/Describe/Execute messages) enables server-side prepared statements, typed parameter encoding, and binary data transfer. The simple protocol sends raw SQL strings.',
    tags: ['skunk', 'postgresql', 'wire-protocol', 'extended-query', 'internals'],
  },
  {
    id: 'scala-db-l4-012',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Skunk',
    question: 'In Skunk, what does `session.execute` (for a Query) vs `session.prepare(query).use(_.execute)` imply about prepared statements?',
    options: [
      'session.execute uses the simple query protocol (no server-side prepared statement); session.prepare creates a named server-side prepared statement for repeated execution',
      'session.execute creates an anonymous prepared statement; session.prepare creates a named one',
      'Both create server-side prepared statements — the difference is only in resource management',
      'session.execute is synchronous; session.prepare is asynchronous',
    ],
    correctAnswer: 0,
    explanation: 'Skunk\'s session.execute for Queries uses unnamed (immediate) prepared statements via the extended protocol. session.prepare explicitly creates and names a server-side prepared statement that can be reused without re-parsing.',
    tags: ['skunk', 'execute', 'prepare', 'prepared-statement', 'internals'],
  },
  {
    id: 'scala-db-l4-013',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Skunk',
    question: 'What is Skunk\'s `Decoder[A]` contravariant in and why does this matter for codec composition?',
    options: [
      'Decoder[A] is a functor (covariant) in A — you can map A => B to get Decoder[B]; it is not contravariant',
      'Decoder[A] is contravariant in A, meaning you can provide a B => A function to get Decoder[B]',
      'Decoder[A] is invariant — it can neither be mapped nor contramapped',
      'Decoder[A] is profunctor, being contravariant in input and covariant in output',
    ],
    correctAnswer: 0,
    explanation: 'Skunk\'s Decoder[A] is covariant (a Functor): `.map(f: A => B)` gives Decoder[B]. This lets you transform decoded values. Encoder[A] is contravariant — you provide A => B to encode A using an Encoder[B].',
    tags: ['skunk', 'decoder', 'encoder', 'variance', 'functor'],
  },
  {
    id: 'scala-db-l4-014',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Skunk',
    question: 'What happens in Skunk when a fiber is cancelled while waiting for a query response?',
    options: [
      'Skunk sends a cancellation message to PostgreSQL and the fiber is safely cancelled; the connection is returned to the pool in a clean state',
      'The connection is poisoned and discarded; a new connection is created',
      'The query continues running on the database; only the Scala fiber is cancelled',
      'Cancellation hangs indefinitely waiting for the database response',
    ],
    correctAnswer: 0,
    explanation: 'Skunk is built with CE3\'s cancellation in mind. When a fiber is cancelled, Skunk sends a PostgreSQL cancel request via a separate socket, properly cleaning up the session for reuse.',
    tags: ['skunk', 'cancellation', 'cats-effect', 'fiber', 'resource-safety'],
  },
  {
    id: 'scala-db-l4-015',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'transactions',
    question: 'What is the "write skew" anomaly in databases and which isolation level prevents it?',
    options: [
      'Two transactions read overlapping data and write to different rows based on what they read, creating an inconsistent state; only SERIALIZABLE prevents it',
      'A transaction writes to a row that was deleted by another concurrent transaction',
      'A transaction\'s write is overwritten by another transaction\'s write without detection',
      'A transaction reads a row and writes back a stale value; REPEATABLE READ prevents it',
    ],
    correctAnswer: 0,
    explanation: 'Write skew: T1 reads rows A and B, T2 reads the same. T1 writes A, T2 writes B. Each is consistent individually but together they violate a business invariant. Only SERIALIZABLE (SSI in PostgreSQL) prevents this.',
    tags: ['transactions', 'write-skew', 'isolation', 'serializable', 'anomaly'],
  },
  {
    id: 'scala-db-l4-016',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'transactions',
    question: 'What is PostgreSQL\'s SSI (Serializable Snapshot Isolation) and how does it differ from traditional 2PL?',
    options: [
      'SSI detects serialization conflicts via dependency tracking without blocking reads/writes; 2PL uses locks that block conflicting operations until the transaction completes',
      'SSI uses timestamps for ordering; 2PL uses row versions',
      'SSI is for distributed databases; 2PL is for single-node PostgreSQL',
      'SSI is used for REPEATABLE READ; 2PL is used for SERIALIZABLE',
    ],
    correctAnswer: 0,
    explanation: 'PostgreSQL\'s SSI provides true serializability without locking via dependency graph analysis. Traditional 2PL (two-phase locking) blocks conflicting operations, causing more lock contention and potential deadlocks.',
    tags: ['postgresql', 'ssi', '2pl', 'serializable', 'concurrency'],
  },
  {
    id: 'scala-db-l4-017',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Quill',
    question: 'Why can\'t you use arbitrary Scala expressions inside Quill\'s `quote` block?',
    options: [
      'Quill\'s macro only understands a limited AST subset — arbitrary Scala code is not translatable to SQL; unsupported expressions cause compile-time errors',
      'Quill only supports pure functions inside quote blocks',
      'quote blocks are evaluated at runtime so complex expressions may cause SQL injection',
      'Quill translates all Scala expressions to SQL; no expressions are unsupported',
    ],
    correctAnswer: 0,
    explanation: 'Quill\'s macro traverses the Scala AST and maps recognized patterns to SQL AST nodes. Scala expressions that have no SQL equivalent (arbitrary method calls, complex pattern matching) cause compile-time macro expansion errors.',
    tags: ['quill', 'macros', 'quote', 'limitations', 'ast'],
  },
  {
    id: 'scala-db-l4-018',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Quill',
    question: 'In Quill, what is the difference between `quote` and `unquote`?',
    options: [
      'quote lifts Scala code to the Quill AST; unquote splices a quoted expression back into another quote block for composition',
      'quote defines a query template; unquote executes it',
      'quote is for compile-time queries; unquote is for runtime queries',
      'They are inverse operations: quote encodes, unquote decodes SQL results',
    ],
    correctAnswer: 0,
    explanation: '`unquote` (or just using a quoted value directly inside another quote) splices one quoted expression into another, enabling query composition. This is key to Quill\'s modularity.',
    codeSnippet: `val activeUsers = quote { query[User].filter(_.active == true) }
val admins = quote {
  unquote(activeUsers).filter(_.role == "admin")
}
// admins = SELECT * FROM users WHERE active = true AND role = 'admin'`,
    tags: ['quill', 'quote', 'unquote', 'composition'],
  },
  {
    id: 'scala-db-l4-019',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Quill',
    question: 'What is Quill\'s "transparent" query execution model and how does it enable zero-overhead abstraction?',
    options: [
      'Quill generates SQL at compile time via macros; at runtime ctx.run(q) executes a pre-built SQL string with no query translation overhead',
      'Quill uses JIT compilation to optimize SQL generation at runtime',
      'Quill caches all generated SQL in a WeakHashMap to avoid recompilation',
      'Quill uses lazy evaluation to defer SQL generation until the last possible moment',
    ],
    correctAnswer: 0,
    explanation: 'Quill\'s macro expands quote blocks into SQL strings at compile time. The generated bytecode calls ctx.run with a literal SQL string and parameters — no runtime AST traversal, making it truly zero-overhead.',
    tags: ['quill', 'compile-time', 'macros', 'zero-overhead', 'performance'],
  },
  {
    id: 'scala-db-l4-020',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'migrations',
    question: 'What is the "locking" mechanism Flyway uses to prevent concurrent migrations in a clustered environment?',
    options: [
      'Flyway uses an UPDATE-based advisory lock on the flyway_schema_history table — only one instance can own the lock row at a time',
      'Flyway uses Java file locks on the migration directory',
      'Flyway uses PostgreSQL advisory locks via pg_try_advisory_lock',
      'Flyway has no locking mechanism and relies on idempotent SQL migrations',
    ],
    correctAnswer: 0,
    explanation: 'Flyway acquires a database-level lock by performing an UPDATE on the schema_history table\'s special lock row. Only the process that can successfully UPDATE the row proceeds with migration.',
    tags: ['flyway', 'migrations', 'locking', 'concurrency', 'cluster'],
  },
  {
    id: 'scala-db-l4-021',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'migrations',
    question: 'What is the risk of having a long-running Flyway migration (e.g., adding an index) in a high-traffic production environment?',
    options: [
      'Long-running DDL can lock the table for the migration duration, blocking application reads/writes and causing timeouts',
      'Flyway times out migrations after 5 minutes by default',
      'Long migrations are automatically split into smaller transactions by Flyway',
      'There is no risk — Flyway migrations run in read-only mode',
    ],
    correctAnswer: 0,
    explanation: 'DDL operations like adding non-concurrent indexes lock the table. For PostgreSQL, use CREATE INDEX CONCURRENTLY in migrations to avoid table locks, though this cannot run inside a transaction.',
    codeSnippet: `-- Flyway migration that doesn't lock the table (PostgreSQL):
-- Note: Must NOT run inside a transaction (set flyway.mixed=true)
CREATE INDEX CONCURRENTLY idx_users_email ON users(email);`,
    tags: ['flyway', 'migrations', 'ddl-lock', 'production', 'concurrently'],
  },
  {
    id: 'scala-db-l4-022',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'migrations',
    question: 'In Flyway, what does `mixed=true` configuration enable and why is it sometimes necessary?',
    options: [
      'It allows a single migration to contain both transactional and non-transactional SQL (like CREATE INDEX CONCURRENTLY in PostgreSQL)',
      'It allows mixing SQL and Java-based migrations in the same version',
      'It allows mixing up and down migrations in the same file',
      'It enables mixing multiple database schemas in a single migration',
    ],
    correctAnswer: 0,
    explanation: 'Some PostgreSQL DDL statements like CREATE INDEX CONCURRENTLY cannot run inside a transaction. Setting `mixed=true` allows migration files containing both transactional and non-transactional statements.',
    tags: ['flyway', 'migrations', 'mixed', 'postgresql', 'concurrently'],
  },
  {
    id: 'scala-db-l4-023',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'JDBC interop',
    question: 'What is the "connection leakage" that can occur with JDBC when using Scala\'s Future and how do you prevent it?',
    options: [
      'If an exception occurs before conn.close() in a Future chain, the connection is never returned; use Resource or scala.util.Using to guarantee cleanup',
      'Futures can create multiple connections simultaneously; use a semaphore to limit concurrency',
      'Future.recover does not call finally blocks; use Try instead',
      'Connection leakage occurs when Futures complete on different threads than they started',
    ],
    correctAnswer: 0,
    explanation: 'If an exception interrupts a Future before conn.close(), the connection leaks. Resource (CE), scala.util.Using, or try-finally patterns guarantee the connection is closed regardless of success or failure.',
    tags: ['jdbc', 'connection-leak', 'future', 'resource-safety'],
  },
  {
    id: 'scala-db-l4-024',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'JDBC interop',
    question: 'What is the purpose of JDBC\'s `Statement.setQueryTimeout(seconds)` and what are its limitations?',
    options: [
      'It sets a timeout for query execution; when exceeded, the driver cancels the query. Limitation: not all drivers implement it, and some only cancel on the next fetch rather than immediately',
      'It sets the total connection lifetime including waiting for a connection from the pool',
      'It configures the network socket timeout for the JDBC connection',
      'It sets the maximum time for all queries in a transaction',
    ],
    correctAnswer: 0,
    explanation: 'setQueryTimeout cancels long-running queries. Implementation varies: PostgreSQL cancels server-side queries; some drivers only stop blocking on the client. Use it alongside network timeouts for robust protection.',
    tags: ['jdbc', 'query-timeout', 'statement', 'limitations'],
  },
  {
    id: 'scala-db-l4-025',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'What is the impact of using `forceInsertAll` vs `++=` in Slick for bulk inserts?',
    options: [
      'forceInsertAll includes auto-increment columns; ++= excludes them. Both generate batch inserts but with different column sets',
      'forceInsertAll uses a single SQL VALUES clause; ++= generates separate INSERT statements',
      'forceInsertAll is more performant because it bypasses validation',
      'They are identical for tables without auto-increment columns',
    ],
    correctAnswer: 0,
    explanation: 'forceInsertAll is the batch version of forceInsert — it includes auto-increment columns in the batch INSERT. Regular ++= excludes auto-increment columns. For tables without AutoInc, they generate similar SQL.',
    tags: ['slick', 'batch-insert', 'force-insert', 'auto-increment'],
  },
  {
    id: 'scala-db-l4-026',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'In Slick, what is the issue with calling `.list` on a query (deprecated API) vs `.result`?',
    options: [
      '.list was a blocking synchronous API in Slick 2.x; .result returns a DBIO[Seq[T]] for async execution in Slick 3.x — using .list will not compile in Slick 3',
      '.list returns a List; .result returns a Seq — they differ in collection type',
      '.list is for in-memory operations; .result hits the database',
      '.list applies a limit automatically; .result does not',
    ],
    correctAnswer: 0,
    explanation: 'Slick 2.x had a synchronous blocking API (.list, .first, etc.). Slick 3.x moved to fully async DBIO-based API (.result, .headOption, etc.). Slick 2 code is not compatible with Slick 3.',
    tags: ['slick', 'migration', 'slick-2', 'slick-3', 'async'],
  },
  {
    id: 'scala-db-l4-027',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'What is the `Implicit Join` pitfall in Slick when filtering across multiple tables?',
    options: [
      'For-comprehension over two tables without a filter produces a CROSS JOIN — if the WHERE filter is missing or incorrect, you get a cartesian product',
      'Implicit joins always generate OUTER JOINs which include NULL rows unexpectedly',
      'Implicit joins cannot be used with Option columns',
      'Implicit joins bypass index usage in PostgreSQL',
    ],
    correctAnswer: 0,
    explanation: 'A for-comprehension over users and orders without a join condition generates an implicit CROSS JOIN, returning M*N rows. Always include the correct filter condition to avoid cartesian products.',
    codeSnippet: `// DANGER — cartesian product if filter is wrong or missing:
for {
  u <- users
  o <- orders
  // Missing: if u.id === o.userId
} yield (u, o)`,
    tags: ['slick', 'cross-join', 'cartesian-product', 'anti-pattern'],
  },
  {
    id: 'scala-db-l4-028',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Doobie',
    question: 'What is the subtle issue with using `cats.effect.std.Queue` with Doobie streaming to process results concurrently?',
    options: [
      'The Doobie stream must complete before enqueued items can be processed if bounded queue fills up, causing deadlock — use unbounded queue or ensure consumer runs concurrently as a separate fiber',
      'Queue does not support ConnectionIO values so it cannot be used with Doobie',
      'Using a Queue with Doobie causes duplicate row processing due to cursor reuse',
      'Queue operations are not atomic with database operations',
    ],
    correctAnswer: 0,
    explanation: 'If you enqueue from a Doobie stream and dequeue in the same fiber, a full bounded queue will block the stream. The solution is to run the consumer as a separate concurrent fiber.',
    tags: ['doobie', 'fs2', 'queue', 'concurrency', 'deadlock'],
  },
  {
    id: 'scala-db-l4-029',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Doobie',
    question: 'In Doobie, what is the difference between `Free[ConnectionOp, A]` and `ConnectionIO[A]`?',
    options: [
      'ConnectionIO[A] is a type alias for Free[ConnectionOp, A] — they are the same type',
      'Free[ConnectionOp, A] is the raw free monad; ConnectionIO is a Kleisli transformer over it',
      'ConnectionIO adds error handling on top of Free[ConnectionOp, A]',
      'Free[ConnectionOp, A] is the internal type; ConnectionIO is the user-facing type with additional methods',
    ],
    correctAnswer: 0,
    explanation: 'ConnectionIO[A] is defined as `type ConnectionIO[A] = Free[ConnectionOp, A]` — they are literally the same type. Doobie uses free monads over ADTs of JDBC operations for its pure representation.',
    tags: ['doobie', 'free-monad', 'connectionio', 'internals', 'type-alias'],
  },
  {
    id: 'scala-db-l4-030',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Doobie',
    question: 'What is Doobie\'s `Twiddler` typeclass used for?',
    options: [
      'It provides isomorphisms between tuples and case classes, enabling automatic conversion between tilde-tuple products (~) and case classes',
      'It handles optional (nullable) columns in result mappings',
      'It converts between Doobie Meta instances and Skunk Codec instances',
      'It provides streaming transformations for large result sets',
    ],
    correctAnswer: 0,
    explanation: 'Doobie\'s Twiddler typeclass (in recent versions) provides the isomorphism between nested product types (A ~ B ~ C) and case classes with matching fields, enabling automatic case class mapping.',
    tags: ['doobie', 'twiddler', 'case-class', 'product-type', 'internals'],
  },
  {
    id: 'scala-db-l4-031',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'connection pooling',
    question: 'What is the impact of setting `dataSource.cachePrepStmts=true` in HikariCP with PostgreSQL?',
    options: [
      'The JDBC driver caches PreparedStatement objects client-side; PostgreSQL already caches plans server-side, so the benefit depends on the driver',
      'It enables connection-level statement caching that dramatically reduces parsing overhead',
      'It stores prepared statement SQL strings in the JVM heap for reuse across connections',
      'HikariCP does not support statement caching; use PgBouncer instead',
    ],
    correctAnswer: 0,
    explanation: 'PostgreSQL JDBC driver\'s statement caching (cachePrepStmts, prepStmtCacheSize) caches PreparedStatement objects client-side. Server-side plan caching is separate. For PostgreSQL, explicit prepared statements via Skunk are more efficient.',
    tags: ['connection-pooling', 'hikaricp', 'prepared-statement-cache', 'postgresql'],
  },
  {
    id: 'scala-db-l4-032',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'connection pooling',
    question: 'What is PgBouncer and how does it complement HikariCP in a production PostgreSQL setup?',
    options: [
      'PgBouncer is a server-side connection pooler that sits between the application and PostgreSQL, providing session/transaction/statement pooling modes that reduce server-side connection overhead',
      'PgBouncer replaces HikariCP for PostgreSQL applications',
      'PgBouncer is a PostgreSQL extension that adds server-side query caching',
      'PgBouncer is an alternative to Flyway for PostgreSQL migrations',
    ],
    correctAnswer: 0,
    explanation: 'PgBouncer is a lightweight PostgreSQL proxy that pools connections at the server. With transaction pooling, many application connections share few server connections. Combined with HikariCP, you get client and server-side pooling.',
    tags: ['connection-pooling', 'pgbouncer', 'postgresql', 'production'],
  },
  {
    id: 'scala-db-l4-033',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'streaming queries',
    question: 'In fs2 with Doobie, what is the risk of calling `.compile.toList` on a large streaming query?',
    options: [
      'toList collects all rows into a List in JVM heap memory, defeating the purpose of streaming and risking OOM for large result sets',
      'toList closes the database connection prematurely',
      'toList cannot be used with Doobie streams — use .compile.drain instead',
      'toList blocks the thread pool until all rows are loaded',
    ],
    correctAnswer: 0,
    explanation: '`.compile.toList` materializes the entire stream into memory. For large result sets, use `.compile.drain` (for side effects) or process in chunks/fold to maintain O(1) memory usage.',
    tags: ['fs2', 'streaming', 'memory', 'compile-to-list', 'oom'],
  },
  {
    id: 'scala-db-l4-034',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'streaming queries',
    question: 'What is the correct approach to run a Doobie streaming query and write results to Kafka without loading all data into memory?',
    options: [
      'Pipe the Doobie stream through an fs2-kafka producer pipe, using .transact for the DB part and the Kafka producer transparently',
      'Collect all results to List, then send to Kafka in a separate step',
      'Use Akka Streams\' Source.fromPublisher with Slick\'s DatabasePublisher for Kafka integration',
      'Use Doobie\'s built-in Kafka integration module',
    ],
    correctAnswer: 0,
    explanation: 'The idiomatic approach is: Doobie query stream → .transact(xa) → fs2-kafka ProducerRecords → .through(KafkaProducer.pipe) → .compile.drain. This streams rows directly to Kafka with O(1) memory.',
    codeSnippet: `sql"SELECT * FROM events"
  .query[Event]
  .stream
  .transact(xa)
  .map(e => ProducerRecords.one(ProducerRecord("topic", e.key, e)))
  .through(KafkaProducer.pipe(producerSettings))
  .compile.drain`,
    tags: ['doobie', 'fs2', 'kafka', 'streaming', 'pipe'],
  },
  {
    id: 'scala-db-l4-035',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Skunk',
    question: 'What is the purpose of Skunk\'s `Typer` and how does it affect type mapping?',
    options: [
      'Typer is responsible for resolving PostgreSQL OID (type identifier) numbers to Skunk codecs; it negotiates type information during session startup',
      'Typer validates Scala type compatibility with SQL types at compile time',
      'Typer provides dynamic typing for JSONB and untyped PostgreSQL columns',
      'Typer is the component that handles type coercions in SQL expressions',
    ],
    correctAnswer: 0,
    explanation: 'PostgreSQL uses OID numbers to identify types. Skunk\'s Typer resolves OIDs to Codecs by querying pg_type during session initialization. Custom types (enums, domains) require registering their OIDs.',
    tags: ['skunk', 'typer', 'oid', 'postgresql', 'type-resolution'],
  },
  {
    id: 'scala-db-l4-036',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Skunk',
    question: 'How do you handle PostgreSQL custom enum types in Skunk?',
    options: [
      'Using enum codecs via Codec.simple with the type\'s OID and a mapping function',
      'Using EnumCodec.of[Status] which auto-derives from a Scala sealed trait',
      'Custom enums are automatically handled via the implicits from skunk-enumeratum',
      'Using varchar codec with manual parsing — Skunk has no native enum support',
    ],
    correctAnswer: 0,
    explanation: 'Skunk handles PostgreSQL enums using Codec.simple with the enum\'s OID (queried from pg_type) and a function mapping the string value to the Scala type. Third-party libraries provide automation.',
    codeSnippet: `val statusCodec: Codec[Status] = Codec.simple[Status](
  encode = _.toString.toLowerCase,
  decode = {
    case "active"   => Right(Active)
    case "inactive" => Right(Inactive)
    case s          => Left(s"Unknown status: $s")
  },
  Types.varchar // or custom OID
)`,
    tags: ['skunk', 'enum', 'postgresql', 'custom-type', 'codec'],
  },
  {
    id: 'scala-db-l4-037',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'What is the `Slick AsyncExecutor` and how does it relate to Slick\'s concurrency model?',
    options: [
      'AsyncExecutor manages Slick\'s internal thread pool for executing DBIO actions; it queues actions when all threads are busy and configures max queue size',
      'AsyncExecutor provides asynchronous execution of SQL statements on the database server',
      'AsyncExecutor enables parallel query execution across multiple connections simultaneously',
      'AsyncExecutor is the reactive streams executor for Slick\'s streaming API',
    ],
    correctAnswer: 0,
    explanation: 'AsyncExecutor is Slick\'s internal thread pool for database operations. It has configurable thread count (matching pool size) and queue size. When the queue is full, new actions block — tuning this is critical for performance.',
    codeSnippet: `val db = Database.forURL(url,
  executor = AsyncExecutor(
    name = "slick-pool",
    minThreads = 10,
    maxThreads = 10,
    queueSize = 1000,
    maxConnections = 10
  )
)`,
    tags: ['slick', 'async-executor', 'thread-pool', 'internals'],
  },
  {
    id: 'scala-db-l4-038',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'What happens in Slick when you call `db.run(action)` on a database whose connection pool is at capacity with no queuing capacity left?',
    options: [
      'A `RejectedExecutionException` is thrown immediately when the AsyncExecutor queue is full',
      'The Future blocks the calling thread until a connection becomes available',
      'Slick returns a failed Future with a TimeoutException after the configured timeout',
      'Slick creates a new connection beyond the pool limit as a temporary measure',
    ],
    correctAnswer: 0,
    explanation: 'When Slick\'s AsyncExecutor queue is full (maxQueue = 0 means no queue), db.run throws RejectedExecutionException. Proper queue sizing prevents this — but an unbounded queue can cause OutOfMemoryError.',
    tags: ['slick', 'async-executor', 'queue', 'rejection', 'production'],
  },
  {
    id: 'scala-db-l4-039',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'JSON codecs for DB',
    question: 'What is the performance implication of using JSONB for all data storage vs normalized relational tables in PostgreSQL?',
    options: [
      'JSONB reduces schema rigidity but has higher storage overhead, slower key-extraction for deeply nested paths, and complex query syntax; normalized tables enable efficient B-tree index scans for common queries',
      'JSONB is always faster because it avoids JOINs',
      'JSONB and normalized tables have identical performance characteristics',
      'JSONB is only slower for writes; reads are always faster with JSONB',
    ],
    correctAnswer: 0,
    explanation: 'JSONB is excellent for semi-structured or varying-schema data but doesn\'t replace normalized tables for structured data. B-tree indexes on typed columns outperform GIN on JSONB for most equality/range queries.',
    tags: ['postgresql', 'jsonb', 'performance', 'normalization', 'tradeoffs'],
  },
  {
    id: 'scala-db-l4-040',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'JSON codecs for DB',
    question: 'How do you implement a PostgreSQL JSONB column that stores heterogeneous data (ADT/sealed trait) in Scala with circe?',
    options: [
      'Use circe\'s discriminator-based encoding with a type field, combined with a custom Decoder that reads the discriminator and routes to the correct case class decoder',
      'Use one JSONB column per ADT case class variant',
      'Store the Scala class name as a separate column and the JSON body in JSONB',
      'ADTs cannot be stored in JSONB — use separate tables with a type tag',
    ],
    correctAnswer: 0,
    explanation: 'circe\'s generic-extras or circe-literal with a type discriminator enables encoding/decoding sealed traits. The discriminator field (e.g., "type": "Circle") routes decoding to the correct variant.',
    codeSnippet: `import io.circe.generic.extras._

implicit val config = Configuration.default.withDiscriminator("type")

@ConfiguredJsonCodec
sealed trait Shape
case class Circle(radius: Double) extends Shape
case class Rect(w: Double, h: Double) extends Shape`,
    tags: ['circe', 'jsonb', 'adt', 'discriminator', 'postgresql'],
  },
  {
    id: 'scala-db-l4-041',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Doobie',
    question: 'What is the issue with using `IO.fromFuture` to integrate a Slick `db.run` result with a Doobie `ConnectionIO` program?',
    options: [
      'IO.fromFuture wraps the Future in IO, but Slick\'s connection is separate from Doobie\'s — they don\'t share a transaction; combining them risks partial commits',
      'IO.fromFuture blocks the calling thread when used with Futures',
      'IO.fromFuture cannot be used inside a ConnectionIO context',
      'There is no issue — IO.fromFuture safely bridges Slick and Doobie',
    ],
    correctAnswer: 0,
    explanation: 'Slick and Doobie use separate connections. You cannot share a single database transaction across both. Mixing them means you have two independent transactions — a distributed transaction problem.',
    tags: ['doobie', 'slick', 'interop', 'transactions', 'anti-pattern'],
  },
  {
    id: 'scala-db-l4-042',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Quill',
    question: 'What is the limitation of Quill\'s `groupBy` when combined with aggregations returning complex types?',
    options: [
      'Quill\'s groupBy supports limited aggregate expressions; complex nested aggregations may require infix SQL or a raw query',
      'Quill\'s groupBy always generates GROUP BY on all non-aggregated columns automatically',
      'groupBy in Quill cannot be combined with having clauses',
      'Quill\'s groupBy only supports Int and Long key types',
    ],
    correctAnswer: 0,
    explanation: 'Quill\'s macro system supports common aggregations (count, sum, avg, min, max) but complex database-specific aggregations (array_agg, string_agg) require infix expressions.',
    codeSnippet: `// Complex aggregation requires infix:
val q = quote {
  query[User]
    .groupBy(_.department)
    .map { case (dept, users) =>
      (dept, infix"string_agg(\${users.map(_.name)}, ',')"
        .as[String])
    }
}`,
    tags: ['quill', 'groupBy', 'aggregation', 'limitation', 'infix'],
  },
  {
    id: 'scala-db-l4-043',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Skunk',
    question: 'How does Skunk handle connection authentication with PostgreSQL SCRAM-SHA-256?',
    options: [
      'Skunk implements the SCRAM-SHA-256 authentication exchange natively using the Cats Effect crypto primitives, as part of the session startup protocol',
      'Skunk delegates authentication to the JDBC driver',
      'Skunk only supports MD5 and password authentication; SCRAM-SHA-256 requires a plugin',
      'Skunk uses TLS client certificates for authentication instead of SCRAM',
    ],
    correctAnswer: 0,
    explanation: 'Skunk implements the full PostgreSQL authentication protocol natively (MD5, SCRAM-SHA-256, and others) as part of its wire protocol implementation, without relying on JDBC.',
    tags: ['skunk', 'authentication', 'scram-sha-256', 'protocol'],
  },
  {
    id: 'scala-db-l4-044',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Skunk',
    question: 'What is the performance advantage of Skunk using binary encoding for PostgreSQL data transfer?',
    options: [
      'Binary format avoids text parsing overhead — integers, timestamps, and other numeric types are transferred in native binary format, reducing serialization/deserialization cost',
      'Binary encoding compresses the data stream reducing network bandwidth',
      'Binary encoding enables parallel data transfer across multiple connections',
      'Binary encoding is only used for BLOB/BYTEA columns; other types use text',
    ],
    correctAnswer: 0,
    explanation: 'Skunk uses PostgreSQL\'s binary wire format for data transfer. This avoids converting numbers, dates, UUIDs, etc. to/from text strings — significantly reducing parse overhead compared to text protocol.',
    tags: ['skunk', 'binary-protocol', 'performance', 'postgresql'],
  },
  {
    id: 'scala-db-l4-045',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'transactions',
    question: 'What is the "lost update" anomaly and how do SELECT FOR UPDATE prevent it?',
    options: [
      'Lost update: T1 reads a row, T2 reads the same row, T1 writes, T2 overwrites T1\'s change without seeing it; FOR UPDATE prevents T2 from reading the row while T1 holds it',
      'Lost update: a transaction\'s changes are not persisted after crash; FOR UPDATE forces immediate disk flush',
      'Lost update: a read query misses recently inserted rows; FOR UPDATE adds the row to the read set',
      'Lost update: concurrent INSERTs generate duplicate primary keys; FOR UPDATE locks the ID generator',
    ],
    correctAnswer: 0,
    explanation: 'The lost update problem occurs in read-modify-write patterns. SELECT FOR UPDATE prevents it by acquiring an exclusive lock on the read row, blocking concurrent modifications until the transaction commits.',
    tags: ['transactions', 'lost-update', 'for-update', 'concurrency'],
  },
  {
    id: 'scala-db-l4-046',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'transactions',
    question: 'What is a "deferred constraint" in PostgreSQL and how does it interact with Doobie transactions?',
    options: [
      'A deferred constraint is checked at transaction commit rather than per-statement, allowing temporarily violated constraints within a transaction; in Doobie this works within a single .transact call',
      'A deferred constraint is applied lazily to existing data but enforced for new inserts',
      'A deferred constraint delays foreign key validation by 100ms',
      'Deferred constraints require SERIALIZABLE isolation in Doobie',
    ],
    correctAnswer: 0,
    explanation: 'PostgreSQL DEFERRABLE INITIALLY DEFERRED constraints are checked at transaction commit. In Doobie, operations within a single .transact call are one transaction, so deferred constraints work correctly.',
    codeSnippet: `-- PostgreSQL deferred constraint:
ALTER TABLE orders ADD CONSTRAINT fk_user FOREIGN KEY (user_id)
  REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED;

-- In Doobie: all operations in one transact can violate FK temporarily:
val prog = for {
  _ <- sql"INSERT INTO orders (user_id, ...) VALUES (999, ...)".update.run
  _ <- sql"INSERT INTO users (id, ...) VALUES (999, ...)".update.run
} yield ()
prog.transact(xa)  // FK checked at COMMIT`,
    tags: ['postgresql', 'deferred-constraint', 'doobie', 'transactions'],
  },
  {
    id: 'scala-db-l4-047',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'JDBC interop',
    question: 'What is the significance of `java.sql.Timestamp` vs `java.time.Instant` in modern JDBC code and how should you handle time zones?',
    options: [
      'java.sql.Timestamp has no timezone awareness and inherits from java.util.Date (problematic); prefer java.time.Instant/OffsetDateTime and use JDBC 4.2\'s setObject with them directly',
      'java.sql.Timestamp is always UTC; java.time.Instant uses the JVM timezone',
      'Both are identical — java.sql.Timestamp internally delegates to java.time.Instant',
      'java.time.Instant requires special JDBC drivers; java.sql.Timestamp works with all JDBC 4.x drivers',
    ],
    correctAnswer: 0,
    explanation: 'java.sql.Timestamp inherits from java.util.Date with JVM-timezone-dependent behavior. JDBC 4.2+ supports java.time types (Instant, LocalDate, OffsetDateTime) directly via setObject/getObject — preferred for correctness.',
    tags: ['jdbc', 'timestamp', 'java-time', 'timezone', 'jdbc-4.2'],
  },
  {
    id: 'scala-db-l4-048',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Doobie',
    question: 'What is the correct way to implement a "read-your-writes" consistency pattern using Doobie and a primary-replica database setup?',
    options: [
      'Perform writes via the primary transactor; for reads that must see those writes, also use the primary transactor; use the replica transactor only for reads that can be eventually consistent',
      'Use SERIALIZABLE isolation on all replica reads to guarantee read-your-writes',
      'Use Doobie\'s built-in ReplicationTransactor which routes writes to primary and reads to replica automatically',
      'read-your-writes is automatic in PostgreSQL replication — all reads see latest writes regardless of which transactor is used',
    ],
    correctAnswer: 0,
    explanation: 'Read-your-writes requires reading from the same connection/server where the write occurred. In a primary-replica setup, reads after a write must go to the primary until the replica is caught up.',
    tags: ['doobie', 'replication', 'read-your-writes', 'consistency'],
  },
  {
    id: 'scala-db-l4-049',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'In Slick, what is the `JoinType` parameter in `join` and what SQL does each type generate?',
    options: [
      'JoinType.Inner → INNER JOIN, JoinType.Left → LEFT OUTER JOIN, JoinType.Right → RIGHT OUTER JOIN, JoinType.Outer → FULL OUTER JOIN',
      'JoinType.Inner → CROSS JOIN, JoinType.Left → LEFT JOIN, JoinType.Right → NATURAL JOIN, JoinType.Outer → OUTER JOIN',
      'JoinType controls the join algorithm (hash, nested loop, merge) not the join type',
      'Slick only supports INNER JOIN and LEFT OUTER JOIN — Right and Full Outer are not supported',
    ],
    correctAnswer: 0,
    explanation: 'Slick\'s join combinators map to SQL join types: joinLeft (LEFT OUTER), joinRight (RIGHT OUTER), joinFull (FULL OUTER), and join (INNER). JoinType enum reflects these options.',
    tags: ['slick', 'join', 'join-type', 'sql-generation'],
  },
  {
    id: 'scala-db-l4-050',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'What is the correct approach for running DDL and DML together safely in Slick, considering that DDL may cause implicit commits in some databases?',
    options: [
      'Run DDL and DML in separate DBIO actions; or use PostgreSQL which supports transactional DDL, allowing DDL in a transaction',
      'Always run DDL and DML in the same DBIO.seq call',
      'Use sqlu for DDL and TableQuery for DML — they are automatically isolated',
      'DDL and DML can never be mixed in Slick',
    ],
    correctAnswer: 0,
    explanation: 'MySQL and some databases implicitly commit on DDL. PostgreSQL supports transactional DDL — you can CREATE TABLE and INSERT in the same transaction and roll back both. In Slick, be aware of the database behavior.',
    tags: ['slick', 'ddl', 'dml', 'transactions', 'database-differences'],
  },
  {
    id: 'scala-db-l4-051',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Quill',
    question: 'In Quill with Scala 3, what changes in the macro system compared to Scala 2?',
    options: [
      'Quill Scala 3 uses inline functions and transparent inlines for SQL generation instead of def macros; compile-time expansion is more explicit and better integrated with the type system',
      'Quill Scala 3 uses runtime reflection instead of compile-time macros for flexibility',
      'Quill Scala 3 generates identical bytecode to Scala 2 — only the macro API changed',
      'Quill Scala 3 supports only async (ZIO) contexts due to macro limitations',
    ],
    correctAnswer: 0,
    explanation: 'Quill\'s Scala 3 port uses the new transparent inline and macro system. The API remains similar but the internals use Scala 3\'s quotes and splices (quote/splice pattern) instead of Scala 2 blackbox macros.',
    tags: ['quill', 'scala-3', 'macros', 'inline'],
  },
  {
    id: 'scala-db-l4-052',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'migrations',
    question: 'What is the risk of using `flyway.setIgnoreMissingMigrations(true)` and when is it appropriate?',
    options: [
      'It allows the application to start even if migration files have been deleted after being applied; risky because you lose the ability to verify what was applied; appropriate for post-cleanup scenarios',
      'It skips migrations that fail checksum validation',
      'It ignores migrations above the current database version',
      'It allows starting with no migration files at all',
    ],
    correctAnswer: 0,
    explanation: 'ignoreMissingMigrations=true prevents Flyway from failing when applied migrations have no corresponding file (e.g., after cleaning old migration files). Use carefully — you lose auditability.',
    tags: ['flyway', 'migrations', 'ignore-missing', 'configuration', 'risk'],
  },
  {
    id: 'scala-db-l4-053',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'migrations',
    question: 'How do you safely add a column to a large PostgreSQL table in production without locking it?',
    options: [
      'Use ALTER TABLE ... ADD COLUMN with a DEFAULT (PostgreSQL 11+ adds columns without rewriting the table if the default is not volatile); for older versions, add nullable without default first',
      'Use Flyway\'s non-transactional migration with CREATE TABLE LIKE and data migration',
      'PostgreSQL always locks tables during ALTER TABLE — schedule during maintenance window',
      'Use pg_repack to restructure the table online without locks',
    ],
    correctAnswer: 0,
    explanation: 'PostgreSQL 11+ handles ADD COLUMN with a constant default without rewriting the table (metadata-only change). For PostgreSQL 10 and earlier, add a nullable column without default, then backfill, then add constraint.',
    codeSnippet: `-- PostgreSQL 11+: safe for large tables
ALTER TABLE users ADD COLUMN preferences JSONB DEFAULT '{}';

-- PostgreSQL 10 and earlier (safe approach):
ALTER TABLE users ADD COLUMN preferences JSONB;  -- step 1: no default
UPDATE users SET preferences = '{}' WHERE preferences IS NULL;  -- step 2: backfill
ALTER TABLE users ALTER COLUMN preferences SET NOT NULL;  -- step 3: add constraint
ALTER TABLE users ALTER COLUMN preferences SET DEFAULT '{}';  -- step 4: add default`,
    tags: ['postgresql', 'migrations', 'alter-table', 'production', 'zero-downtime'],
  },
  {
    id: 'scala-db-l4-054',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Doobie',
    question: 'What is the performance implication of using Doobie\'s `IO.blocking` vs using a separate cached thread pool for JDBC calls?',
    options: [
      'IO.blocking uses CE3\'s built-in blocking pool with automatic thread management; a cached pool may grow unboundedly under load, while CE3\'s pool is bounded and managed',
      'IO.blocking creates a new thread per call; a cached pool reuses threads — IO.blocking is always slower',
      'They are performance-equivalent; the choice is purely stylistic',
      'A separate cached pool is required for Doobie — IO.blocking cannot be used with JDBC',
    ],
    correctAnswer: 0,
    explanation: 'CE3\'s IO.blocking uses a managed blocking thread pool that grows and shrinks based on demand but is controlled. An unbounded CachedThreadPool can create thousands of threads under load, causing memory and scheduling issues.',
    tags: ['doobie', 'cats-effect-3', 'io-blocking', 'thread-pool', 'performance'],
  },
  {
    id: 'scala-db-l4-055',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'JDBC interop',
    question: 'What is JDBC\'s `RowId` type and when is it useful?',
    options: [
      'RowId is a database-specific identifier for a physical row location; it provides the fastest possible row retrieval but is not portable across databases and may become invalid after row movement',
      'RowId is a database-independent UUID assigned to every row for auditing purposes',
      'RowId is JDBC\'s abstraction for auto-increment primary keys',
      'RowId is used to identify rows in result sets for scrollable cursor navigation',
    ],
    correctAnswer: 0,
    explanation: 'JDBC\'s RowId (java.sql.RowId) represents a database-specific physical row identifier (like Oracle\'s ROWID). It enables direct row lookup but is not portable and may be invalidated by compaction or migration.',
    tags: ['jdbc', 'rowid', 'advanced', 'portability'],
  },
  {
    id: 'scala-db-l4-056',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'streaming queries',
    question: 'In Doobie, what is the behavior of the stream when using `.transactWith(xa, TransactorStrategy.void)` vs the default strategy?',
    options: [
      'void strategy runs the stream without any transaction (no BEGIN/COMMIT); the default strategy wraps in a transaction — void is useful when you want to control transactions manually',
      'void strategy discards all stream results; default strategy collects them',
      'void strategy uses a read-only transaction; default strategy uses read-write',
      'void strategy enables streaming; default strategy does not support streaming',
    ],
    correctAnswer: 0,
    explanation: 'Transactor.Strategy.void runs ConnectionIO without any transaction management (no auto-commit setting, no BEGIN/COMMIT). Useful when you need manual control or when the DB operation doesn\'t need a transaction.',
    tags: ['doobie', 'streaming', 'transactor-strategy', 'void', 'transactions'],
  },
  {
    id: 'scala-db-l4-057',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'What is the difference between Slick\'s `selectStatement` and `updateStatement` debugging methods?',
    options: [
      'selectStatement returns the SQL string that would be generated for a query; updateStatement returns the SQL for a DML operation — both are useful for debugging generated SQL without executing',
      'selectStatement runs the query and returns the result as a String; updateStatement runs the update and returns the SQL',
      'selectStatement is available in all profiles; updateStatement is PostgreSQL-specific',
      'These methods do not exist in Slick — use .result.statements instead',
    ],
    correctAnswer: 3,
    explanation: 'In Slick, you use `.result.statements` on a query to get the SQL strings, or `.statements` on a DML action. These return Iterable[String] with the generated SQL without executing the query.',
    codeSnippet: `// Get generated SQL without executing:
val sql: Iterable[String] = users.filter(_.id === 1).result.statements
println(sql.mkString)

val insertSql = (users += User(0, "Alice")).statements
println(insertSql.mkString)`,
    tags: ['slick', 'debugging', 'sql-generation', 'statements'],
  },
  {
    id: 'scala-db-l4-058',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Skunk',
    question: 'How does Skunk\'s `Session.pooled` handle connection failures during pool initialization?',
    options: [
      'Session.pooled returns a Resource that fails immediately if initial connections cannot be established, propagating the error to the calling IO',
      'Session.pooled creates the pool lazily — connections are only established on first use',
      'Session.pooled retries connection establishment indefinitely until successful',
      'Session.pooled creates the pool with zero connections initially and adds connections on demand',
    ],
    correctAnswer: 0,
    explanation: 'Skunk\'s pooled session is a Resource. If the initial connection cannot be established during startup, the Resource acquisition fails with an appropriate error — the application should handle this with retry logic.',
    tags: ['skunk', 'session', 'pooled', 'error-handling', 'startup'],
  },
  {
    id: 'scala-db-l4-059',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'connection pooling',
    question: 'What is the "pool livelock" scenario in HikariCP and how does it occur?',
    options: [
      'All threads are waiting for connections that are held by other threads also waiting — a circular dependency that prevents any progress, similar to deadlock but without full blocking',
      'Livelock occurs when connections are rapidly acquired and released but queries never complete',
      'Livelock is when keepalive queries consume all available connections',
      'Pool livelock cannot occur in HikariCP due to its timeout mechanism',
    ],
    correctAnswer: 0,
    explanation: 'Pool livelock occurs in complex transactional code where T1 holds connection C1 and waits for C2, while T2 holds C2 and waits for C1 (or C3, etc.). Solution: single connection per transaction, careful ordering.',
    tags: ['connection-pooling', 'hikaricp', 'livelock', 'deadlock', 'concurrency'],
  },
  {
    id: 'scala-db-l4-060',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'JSON codecs for DB',
    question: 'What is the performance implication of decoding JSONB to a full Scala case class vs extracting specific fields using PostgreSQL JSON operators?',
    options: [
      'Decoding the full document transfers more data over the network and requires full parse; PostgreSQL JSON operators extract specific fields server-side reducing data transfer and parse overhead',
      'Full case class decoding is faster because Skunk/Doobie use binary protocol',
      'There is no performance difference — PostgreSQL caches the parsed JSONB in memory',
      'PostgreSQL JSON operators are slower due to additional query planning overhead',
    ],
    correctAnswer: 0,
    explanation: 'When you only need one field from a large JSONB document, using `profile->\'field\'` or `jsonb_extract_path` server-side transfers only that field\'s value, reducing network I/O and client parse time.',
    codeSnippet: `-- Extract only one field server-side:
sql"SELECT profile->>'email' FROM users WHERE id = $id".query[String]

-- vs loading the whole document:
sql"SELECT profile FROM users WHERE id = $id".query[Profile]`,
    tags: ['postgresql', 'jsonb', 'performance', 'json-operators', 'data-transfer'],
  },
  {
    id: 'scala-db-l4-061',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Doobie',
    question: 'In Doobie, what is `FR0` and how does it differ from `fr0`?',
    options: [
      'fr0 creates a Fragment with no arguments (const fragment); FR0 is the Fragment type for no-argument fragments — both refer to the zero-parameter case of Fragment composition',
      'FR0 is the internal representation; fr0 is the user-facing interpolator',
      'fr0 generates parameterized SQL; FR0 generates literal SQL without parameters',
      'FR0 uses the JDBC simple statement; fr0 uses prepared statements',
    ],
    correctAnswer: 0,
    explanation: '`fr0` (sometimes called `const`) creates a Fragment from a constant string with no parameters — useful for building safe non-parameterized SQL fragments. FR0 is not a separate type but refers to this zero-parameter case.',
    codeSnippet: `// fr0 for constant SQL fragments (no parameters):
val orderByClause = fr0"ORDER BY name ASC"
val query = fr"SELECT * FROM users" ++ orderByClause`,
    tags: ['doobie', 'fr0', 'fragments', 'const'],
  },
  {
    id: 'scala-db-l4-062',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'What is the subtle bug in this Slick code: `users.filter(_.name === name).result.head`?',
    options: [
      'It will throw NoSuchElementException if no user has that name, even though headOption would return None safely; and it fetches all matching rows (no LIMIT 1) before taking the first',
      'The `===` operator should be `==` for String comparisons',
      'head is not defined on DBIO; use result.head separately',
      'The query will fail to compile because name must be wrapped in Option',
    ],
    correctAnswer: 0,
    explanation: 'Two bugs: (1) `.result.head` throws NoSuchElementException instead of returning None — use `.result.headOption`. (2) It generates no LIMIT 1, fetching all matching rows unnecessarily. Use `.take(1).result.headOption`.',
    codeSnippet: `// Buggy:
users.filter(_.name === name).result.head

// Fixed:
users.filter(_.name === name).take(1).result.headOption`,
    tags: ['slick', 'head', 'bug', 'no-such-element', 'limit'],
  },
  {
    id: 'scala-db-l4-063',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'migrations',
    question: 'What is the "expand and contract" pattern for zero-downtime schema migrations?',
    options: [
      'Expand: add new columns/tables without removing old ones; deploy new app code; Contract: remove old columns/tables in a subsequent release after all code uses new schema',
      'Expand: increase column sizes; Contract: add constraints after data validation',
      'Expand: add indexes before data migration; Contract: remove indexes after migration',
      'Expand: use wider types (e.g., INT -> BIGINT); Contract: remove the old column type',
    ],
    correctAnswer: 0,
    explanation: 'The expand-contract pattern enables zero-downtime migrations: Expand phase adds new structures (compatible with old code), deploy new code, then Contract phase removes old structures after all instances run new code.',
    tags: ['migrations', 'zero-downtime', 'expand-contract', 'schema-evolution'],
  },
  {
    id: 'scala-db-l4-064',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Quill',
    question: 'In Quill, what is the behavior when you use `==` inside a quote block with an Option field?',
    options: [
      'Quill generates IS NULL for None and = value for Some — it handles Option equality correctly in WHERE clauses',
      'Using == with Option causes a compile error — you must use contains or isEmpty',
      'Quill generates COALESCE to handle NULL comparison with ==',
      'Option fields cannot be compared in Quill quote blocks',
    ],
    correctAnswer: 0,
    explanation: 'Quill is aware of Option semantics. When comparing an Option column with a lifted Option value, it generates IS NULL for None and = $value for Some(value) automatically.',
    codeSnippet: `val maybeAge: Option[Int] = Some(30)
val q = quote {
  query[User].filter(u => u.age == lift(maybeAge))
}
// Generated: SELECT ... WHERE age = 30 (or WHERE age IS NULL if None)`,
    tags: ['quill', 'option', 'null', 'equality', 'sql-generation'],
  },
  {
    id: 'scala-db-l4-065',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Skunk',
    question: 'How does Skunk handle PostgreSQL\'s `COPY TO STDOUT` for bulk data export?',
    options: [
      'Using session.pipe with a CopyOutCodec to stream rows directly from PostgreSQL COPY TO STDOUT through an fs2 Stream',
      'COPY TO STDOUT is not supported in Skunk — use SELECT ... LIMIT for bulk export',
      'Using session.copyOut which returns IO[Array[Byte]] containing all rows',
      'Using the postgres-copy extension module for Skunk',
    ],
    correctAnswer: 0,
    explanation: 'Skunk supports PostgreSQL\'s COPY protocol for efficient bulk data transfer. The CopyOut operation streams data from PostgreSQL directly, bypassing row-by-row parsing for maximum throughput.',
    tags: ['skunk', 'copy', 'postgresql', 'bulk-export', 'streaming'],
  },
  {
    id: 'scala-db-l4-066',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'transactions',
    question: 'What is the difference between `NOWAIT` and `SKIP LOCKED` in PostgreSQL SELECT FOR UPDATE?',
    options: [
      'NOWAIT fails immediately if the lock cannot be acquired; SKIP LOCKED skips locked rows and continues — SKIP LOCKED is useful for job queue patterns',
      'NOWAIT waits up to 1ms; SKIP LOCKED waits indefinitely',
      'NOWAIT uses optimistic locking; SKIP LOCKED uses pessimistic locking',
      'They are identical — both skip locked rows without waiting',
    ],
    correctAnswer: 0,
    explanation: 'FOR UPDATE NOWAIT raises an error immediately if a row is locked. FOR UPDATE SKIP LOCKED skips locked rows (returns only unlocked rows) — perfect for concurrent job queue processing where workers should not contend.',
    codeSnippet: `-- Job queue pattern with SKIP LOCKED:
SELECT * FROM jobs
WHERE status = 'pending'
ORDER BY created_at
LIMIT 10
FOR UPDATE SKIP LOCKED;`,
    tags: ['postgresql', 'for-update', 'nowait', 'skip-locked', 'job-queue'],
  },
  {
    id: 'scala-db-l4-067',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Doobie',
    question: 'In Doobie, what happens when the database connection is lost mid-stream while processing a large streaming query?',
    options: [
      'The fs2 Stream fails with a SQLException; the error propagates to the IO and must be handled at the transact level — the stream cannot automatically reconnect',
      'Doobie automatically reconnects and continues the stream from the last successful row',
      'The stream silently terminates, returning rows fetched before the connection loss',
      'The stream switches to a backup connection from the pool',
    ],
    correctAnswer: 0,
    explanation: 'Doobie streams are tied to a single connection (required for cursor). A connection loss causes a SQLException that propagates through the stream. Recovery requires restarting the entire query from the beginning.',
    tags: ['doobie', 'streaming', 'connection-loss', 'error-handling', 'resilience'],
  },
  {
    id: 'scala-db-l4-068',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'What is Slick\'s `into` method when combined with `returning` and how does it differ from just `returning`?',
    options: [
      'returning gives back the specified column value(s) from the database; into maps those returned values back into the original object type (e.g., setting the generated ID on the inserted case class)',
      'into is used for SQL INTO syntax in stored procedure calls; returning is for INSERT RETURNING',
      'They are identical — into is just an alias for returning',
      'into is for Scala 3; returning is for Scala 2',
    ],
    correctAnswer: 0,
    explanation: '`returning table.map(_.id)` gets the generated ID as a separate value. Adding `into ((row, id) => row.copy(id = id))` maps the ID back into the inserted row type, returning the complete object with the database-assigned ID.',
    codeSnippet: `val insertAndGet =
  (users returning users.map(_.id) into ((user, id) => user.copy(id = id))) += newUser
// Returns: Future[User] with the DB-assigned id`,
    tags: ['slick', 'returning', 'into', 'insert', 'generated-key'],
  },
  {
    id: 'scala-db-l4-069',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'connection pooling',
    question: 'What is the behavior of HikariCP when the database server restarts and how do you configure proper recovery?',
    options: [
      'HikariCP detects broken connections via keepalive and connection validation, creating new connections as needed; configure initializationFailTimeout=-1 to not fail on startup if DB is temporarily unavailable',
      'HikariCP immediately terminates the application when the database restarts',
      'HikariCP caches the last successful query results during outage',
      'HikariCP automatically retries failed queries against a hot standby',
    ],
    correctAnswer: 0,
    explanation: 'HikariCP evicts failed connections and creates new ones. `initializationFailTimeout=-1` disables startup failure if the DB is unavailable, allowing the app to start and wait. Configure keepaliveTime and maxLifetime for robust recovery.',
    tags: ['hikaricp', 'connection-pooling', 'resilience', 'database-restart'],
  },
  {
    id: 'scala-db-l4-070',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'streaming queries',
    question: 'What is the "tee" pattern in fs2 streaming and how is it applied to database streaming in Doobie?',
    options: [
      'The tee pattern (Stream.tee or .observe) sends each element to two consumers simultaneously — e.g., writing to a DB stream and logging each row without buffering',
      'Tee splits a stream into two separate streams for parallel processing',
      'Tee is a PostgreSQL feature for real-time stream replication',
      'Tee is fs2\'s term for the cursor position in a streaming query',
    ],
    correctAnswer: 0,
    explanation: '`stream.observe(sink)` in fs2 sends each element to a sink (for side effects like logging) while also continuing the main stream. This enables non-destructive inspection of streaming database results.',
    codeSnippet: `sql"SELECT * FROM events"
  .query[Event]
  .stream
  .transact(xa)
  .observe(fs2.io.stdout(using EventCodec))  // log each event
  .evalMap(processEvent)
  .compile.drain`,
    tags: ['fs2', 'streaming', 'tee', 'observe', 'doobie'],
  },
  {
    id: 'scala-db-l4-071',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Quill',
    question: 'In Quill, what is the difference between `ctx.executeQuery` and `ctx.run` for advanced use cases?',
    options: [
      'ctx.run takes a quoted query; ctx.executeQuery takes raw SQL string and parameter list — used for SQL not expressible in Quill\'s AST',
      'ctx.executeQuery returns results as List[Map[String, Any]]; ctx.run returns typed results',
      'ctx.executeQuery runs asynchronously; ctx.run is synchronous',
      'They are identical — executeQuery is deprecated in favor of run',
    ],
    correctAnswer: 0,
    explanation: 'Quill provides `executeQuery` (and `executeAction`) for raw SQL execution with typed results. This is the escape hatch for queries that cannot be expressed in Quill\'s DSL.',
    codeSnippet: `// Raw SQL with typed result:
ctx.executeQuery(
  "SELECT id, name FROM users WHERE lower(name) = lower(?)",
  row => User(row.getInt("id"), row.getString("name")),
  ps => ps.setString(1, name)
)`,
    tags: ['quill', 'execute-query', 'raw-sql', 'escape-hatch'],
  },
  {
    id: 'scala-db-l4-072',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'In Slick, what is the purpose of `withTransactionIsolation` in a DBIO action?',
    options: [
      'It sets the transaction isolation level for the wrapped DBIO action, e.g., withTransactionIsolation(Serializable) on the transactionally action',
      'It is not a Slick method — use raw JDBC to set isolation level',
      'It wraps the action to automatically retry on serialization failures',
      'It validates that the current isolation level matches the specified level before executing',
    ],
    correctAnswer: 0,
    explanation: 'Slick\'s `.transactionally.withTransactionIsolation(level)` sets the isolation level on the transaction. Available levels are defined in slick.jdbc.TransactionIsolation.',
    codeSnippet: `import slick.jdbc.TransactionIsolation

val action = (for {
  _ <- users += newUser
  _ <- accounts += newAccount
} yield ())
  .transactionally
  .withTransactionIsolation(TransactionIsolation.Serializable)`,
    tags: ['slick', 'transaction-isolation', 'dbio', 'transactions'],
  },
  {
    id: 'scala-db-l4-073',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Doobie',
    question: 'What is the correct way to handle PostgreSQL error codes (PSQLException) in Doobie for specific constraint violations?',
    options: [
      'Catch the exception in the IO layer, check e.getSQLState or e.getServerErrorMessage for the constraint name, and convert to domain-specific errors',
      'Use Doobie\'s PSQLExceptionMapper typeclass to map constraint violations to Scala types',
      'Use sql"...ON CONFLICT DO NOTHING" to avoid exceptions for constraint violations',
      'Catch java.sql.SQLIntegrityConstraintViolationException which wraps PSQLException',
    ],
    correctAnswer: 0,
    explanation: 'After .transact(xa) returns IO, you handle database errors with .handleErrorWith. PSQLException (from the PostgreSQL driver) provides SQLState codes and ServerErrorMessage with constraint names.',
    codeSnippet: `import org.postgresql.util.PSQLException

program.transact(xa).handleErrorWith {
  case e: PSQLException if e.getSQLState == "23505" =>
    // Unique constraint violation
    val constraint = e.getServerErrorMessage.getConstraint
    IO.raiseError(DuplicateEntityError(constraint))
  case other => IO.raiseError(other)
}`,
    tags: ['doobie', 'postgresql', 'psqlexception', 'constraint-violation', 'error-handling'],
  },
  {
    id: 'scala-db-l4-074',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Skunk',
    question: 'In Skunk, what is the role of the `Trace[F]` typeclass in Session creation?',
    options: [
      'Trace[F] provides distributed tracing capability; Skunk instruments all SQL operations with trace spans, requiring a Natchez Trace instance (or noop for no tracing)',
      'Trace[F] provides query logging to the application log',
      'Trace[F] enables distributed transactions across multiple Skunk sessions',
      'Trace[F] is required for SSL/TLS connection setup',
    ],
    correctAnswer: 0,
    explanation: 'Skunk requires a `Trace[F]` instance for distributed tracing via Natchez. Every database operation creates a trace span. Use `Trace.Implicits.noop` if you don\'t want tracing.',
    codeSnippet: `import natchez.Trace.Implicits.noop

Session.single[IO](
  host = "localhost",
  port = 5432,
  user = "postgres",
  database = "mydb"
  // Trace[IO] provided by noop import
)`,
    tags: ['skunk', 'trace', 'natchez', 'distributed-tracing', 'observability'],
  },
  {
    id: 'scala-db-l4-075',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'JSON codecs for DB',
    question: 'What is the performance impact of using `circe.Encoder.apply.apply(value).noSpaces` vs `Printer.noSpaces.print(value.asJson)` for encoding JSONB in Doobie?',
    options: [
      'Both produce the same string; noSpaces is a Printer configuration. The difference is API style, not performance — modern circe versions optimize both paths similarly',
      'noSpaces is significantly faster because it skips whitespace generation',
      'Printer.noSpaces.print is faster because it avoids the implicit resolution overhead of asJson',
      'Using encode directly on the Encoder is always faster than going through the Printer',
    ],
    correctAnswer: 0,
    explanation: 'In circe, `.asJson.noSpaces` and `Printer.noSpaces.print(value.asJson)` both use the same underlying encoder. The performance is equivalent — choose based on code clarity.',
    tags: ['circe', 'jsonb', 'encoding', 'performance', 'printer'],
  },
  {
    id: 'scala-db-l4-076',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'JDBC interop',
    question: 'What is the `java.sql.SQLXML` type in JDBC and when is it appropriate to use it over CLOB for XML data?',
    options: [
      'SQLXML represents XML data with database-aware parsing; it enables XPath/XQuery operations server-side vs CLOB which is raw text with no XML semantics',
      'SQLXML is faster to read than CLOB for large documents',
      'SQLXML automatically validates XML against a schema; CLOB does not',
      'SQLXML and CLOB are functionally identical — SQLXML is just a semantic marker',
    ],
    correctAnswer: 0,
    explanation: 'java.sql.SQLXML represents XML in a database-aware manner, enabling server-side XML processing (XPath queries, XQuery). CLOB stores XML as raw text without any XML-specific database operations.',
    tags: ['jdbc', 'sqlxml', 'clob', 'xml', 'advanced'],
  },
  {
    id: 'scala-db-l4-077',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'In Slick, what is the behavior of `DBIO.sequence` vs `DBIO.traverseSequentially` and when does the difference matter?',
    options: [
      'DBIO.sequence evaluates all actions eagerly in a for-comprehension; traverseSequentially applies an action-returning function to a collection sequentially — traverseSequentially is more lazy and avoids building an intermediate list of actions',
      'DBIO.sequence runs actions in parallel; traverseSequentially runs them one at a time',
      'They produce identical results and behavior',
      'DBIO.sequence is for Seq[DBIO[A]]; traverseSequentially is for DBIO[Seq[A]]',
    ],
    correctAnswer: 0,
    explanation: 'Both are sequential, but DBIO.traverseSequentially applies f: A => DBIO[B] to each element lazily as it chains. This is important for large collections where materializing all DBIO[B] objects at once would use excessive memory.',
    codeSnippet: `// traverseSequentially for large collections:
val ids: List[Int] = (1 to 100000).toList
val action: DBIO[List[User]] =
  DBIO.traverseSequentially(ids)(id => users.filter(_.id === id).result.headOption)`,
    tags: ['slick', 'dbio', 'sequence', 'traverse-sequentially', 'performance'],
  },
  {
    id: 'scala-db-l4-078',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'migrations',
    question: 'What is the "shadow table" technique for zero-downtime column type changes in PostgreSQL?',
    options: [
      'Add a new column of the target type, backfill it via trigger/batch update, swap the column names, then drop the old column — all without downtime',
      'Create a view that casts the old column type to the new type for application transparency',
      'Use pg_alter_type to change the column type in background without locking',
      'Temporarily create a shadow database, perform the migration, and switch DNS',
    ],
    correctAnswer: 0,
    explanation: 'To change a column type without downtime: (1) ADD new_col NEW_TYPE, (2) create trigger to sync old→new, (3) batch backfill, (4) deploy code using new_col, (5) DROP old_col, (6) RENAME new_col. No table lock required.',
    tags: ['postgresql', 'migrations', 'zero-downtime', 'column-type-change', 'shadow-column'],
  },
  {
    id: 'scala-db-l4-079',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Doobie',
    question: 'What is the performance implication of Doobie\'s `Update[A].updateMany` vs calling `.update.run` in a for-comprehension loop?',
    options: [
      'updateMany uses JDBC batch execution (addBatch/executeBatch) sending all parameters in one network round trip; a loop calls executeBatch once per item, resulting in N round trips',
      'updateMany is slightly slower due to batch setup overhead for small collections',
      'They have identical performance — Doobie optimizes the loop automatically',
      'updateMany is only faster for > 1000 rows; below that, the loop is equally efficient',
    ],
    correctAnswer: 0,
    explanation: 'JDBC batch execution dramatically reduces network round trips. updateMany sends all rows in a single batch (one network exchange), while individual `.run` calls create N round trips. The difference is significant for large collections.',
    tags: ['doobie', 'update-many', 'batch', 'performance', 'jdbc'],
  },
  {
    id: 'scala-db-l4-080',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Quill',
    question: 'In Quill with ZIO, how does `ZioJdbcContext.run` handle transactionality?',
    options: [
      'ZioJdbcContext.run uses ZIO\'s Has[DataSource] dependency; transactions require explicit ZIO.service[Connection] or using ctx.transaction { ... }',
      'All ZioJdbcContext.run calls automatically participate in the current transaction',
      'ZioJdbcContext never uses transactions — each run is autocommit',
      'ZioJdbcContext uses ZIO\'s STM for all transactional operations',
    ],
    correctAnswer: 0,
    explanation: 'ZIO-Quill contexts require explicit transaction demarcation using ctx.transaction { ... } which provides a scoped Connection. Outside a transaction block, each run uses a separate connection with autocommit.',
    codeSnippet: `ctx.transaction {
  for {
    _ <- ctx.run(quote(query[User].insertValue(lift(user))))
    _ <- ctx.run(quote(query[Audit].insertValue(lift(audit))))
  } yield ()
}`,
    tags: ['quill', 'zio', 'transactions', 'zio-quill'],
  },
  {
    id: 'scala-db-l4-081',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'streaming queries',
    question: 'What is the "chunking" strategy in fs2 streaming with Doobie and how does it affect memory usage and throughput?',
    options: [
      'Chunks are contiguous memory segments; larger chunks improve throughput (fewer context switches) but use more memory. streamWithChunkSize controls the JDBC fetch size which determines chunk granularity',
      'Chunking splits the SQL query into multiple partial queries executed in parallel',
      'Chunks in fs2 are always exactly 1 element when using Doobie streams',
      'Chunk size in Doobie is fixed at 512 rows and cannot be configured',
    ],
    correctAnswer: 0,
    explanation: 'fs2 Chunks are contiguous in-memory arrays. streamWithChunkSize(n) fetches n rows per JDBC round trip, forming chunks of size n. Larger chunks improve throughput but use more heap. Tune based on row size and memory constraints.',
    codeSnippet: `// Tune chunk size based on row size and available memory:
val stream = sql"SELECT * FROM large_table"
  .query[LargeRow]
  .streamWithChunkSize(256)  // 256 rows per JDBC fetch
  .transact(xa)
  .chunks
  .evalMap(chunk => IO.println(s"Processing chunk of \${chunk.size}"))
  .compile.drain`,
    tags: ['fs2', 'streaming', 'chunks', 'doobie', 'memory', 'performance'],
  },
  {
    id: 'scala-db-l4-082',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Skunk',
    question: 'What happens in Skunk when you define a SQL query with more parameters in the interpolator than in the Codec type?',
    options: [
      'A compile-time error (or runtime error during session.prepare) because the number of parameters in the SQL must exactly match the Codec arity',
      'Extra parameters are ignored by PostgreSQL',
      'Skunk creates a Codec[Void] for unused parameters automatically',
      'Skunk merges the extra parameters into a tuple with the existing ones',
    ],
    correctAnswer: 0,
    explanation: 'Skunk\'s type system ensures the SQL parameter count matches the encoder\'s arity. A mismatch will cause an error during query construction (often detectable at compile time with proper type annotations).',
    tags: ['skunk', 'type-safety', 'parameters', 'codec', 'arity'],
  },
  {
    id: 'scala-db-l4-083',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'transactions',
    question: 'What is the difference between `COMMIT` and `COMMIT AND CHAIN` in PostgreSQL and how does it affect application-level transaction management?',
    options: [
      'COMMIT ends the current transaction; COMMIT AND CHAIN commits and immediately begins a new transaction with the same isolation level, reducing round trips for sequential transactions',
      'COMMIT AND CHAIN commits the current and all nested savepoints; COMMIT only commits the outer transaction',
      'They are identical — AND CHAIN is just documentation syntax',
      'COMMIT AND CHAIN is only available in PostgreSQL 14+ for logical replication',
    ],
    correctAnswer: 0,
    explanation: 'COMMIT AND CHAIN (PostgreSQL 14+, SQL standard) atomically commits and starts a new transaction. This reduces the overhead of separate COMMIT + BEGIN round trips for applications that continuously process transactions.',
    tags: ['postgresql', 'transactions', 'commit-and-chain', 'performance'],
  },
  {
    id: 'scala-db-l4-084',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'What is the behavior of Slick\'s `DBIO.from(Future)` and when should you use it vs native DBIO composition?',
    options: [
      'DBIO.from(future) lifts a Future into DBIO for interop; it runs the Future outside the database transaction, so transaction semantics do not apply to the Future\'s effects',
      'DBIO.from runs the Future on the database thread pool',
      'DBIO.from integrates Future results into the current database transaction',
      'DBIO.from is equivalent to DBIO.successful — it materializes the Future immediately',
    ],
    correctAnswer: 0,
    explanation: 'DBIO.from(future) wraps a pre-existing Future in DBIO for sequencing. Critical: the Future\'s effects are outside the database transaction. Use sparingly and only for non-transactional operations.',
    codeSnippet: `val externalCall: Future[String] = httpClient.get("...")

val combined = for {
  user   <- users.filter(_.id === id).result.head
  external <- DBIO.from(externalCall)  // NOT in the transaction!
  _      <- logs += Log(user.id, external)
} yield ()`,
    tags: ['slick', 'dbio-from', 'future', 'interop', 'transactions'],
  },
  {
    id: 'scala-db-l4-085',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Doobie',
    question: 'In Doobie, how do you implement a custom `Meta` instance for a PostgreSQL range type (e.g., int4range)?',
    options: [
      'Create a Meta[MyRange] using Meta[String].timap that parses the PostgreSQL range literal format, or use the doobie-postgres module which provides range support',
      'Implement the PgRangeCodec[MyRange] trait from doobie-postgres',
      'PostgreSQL range types cannot be used in Doobie — use BETWEEN in SQL instead',
      'Use the @PgRange annotation on a case class field',
    ],
    correctAnswer: 0,
    explanation: 'For PostgreSQL range types, you can create a custom Meta by mapping from the String representation (e.g., "[1,10)") using timap. The doobie-postgres module provides built-in support for common range types.',
    codeSnippet: `case class IntRange(lower: Int, upper: Int)

// Manual Meta for int4range:
implicit val intRangeMeta: Meta[IntRange] =
  Meta[String].timap(
    str => {
      val pattern = "\\[(\\d+),(\\d+)\\)".r
      val pattern(lo, hi) = str
      IntRange(lo.toInt, hi.toInt)
    },
    r => s"[\${r.lower},\${r.upper})"
  )`,
    tags: ['doobie', 'meta', 'postgresql', 'range-type', 'custom'],
  },
  {
    id: 'scala-db-l4-086',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'connection pooling',
    question: 'What is the "statement timeout" vs "lock timeout" vs "idle in transaction session timeout" in PostgreSQL and how do you set them in Doobie?',
    options: [
      'statement_timeout cancels long queries; lock_timeout fails if a lock cannot be acquired within the limit; idle_in_transaction_session_timeout closes sessions idle inside a transaction; all set via SET command in Doobie using sql"SET ..." before queries',
      'All three are configured via HikariCP properties',
      'These are connection-level settings that can only be set in postgresql.conf',
      'Doobie does not support PostgreSQL timeout settings',
    ],
    correctAnswer: 0,
    explanation: 'These PostgreSQL timeout settings can be set per-session using SQL commands. In Doobie, you execute SET commands as ConnectionIO operations before your queries within the same transaction.',
    codeSnippet: `val program = for {
  _ <- sql"SET statement_timeout = '5s'".update.run
  _ <- sql"SET lock_timeout = '1s'".update.run
  r <- sql"SELECT * FROM users".query[User].to[List]
} yield r`,
    tags: ['postgresql', 'timeout', 'doobie', 'connection-settings'],
  },
  {
    id: 'scala-db-l4-087',
    language: 'scala',
    level: 'level4',
    category: 'Database & Persistence',
    subcategory: 'Quill',
    question: 'What is Quill\'s behavior when a `quote` block references a Scala value that is not `lift`-ed?',
    options: [
      'The value is inlined as a SQL literal at compile time (not a prepared statement parameter) — this is a potential SQL injection risk for non-constant values and causes a compile warning',
      'The compilation fails with an error requiring all runtime values to be lifted',
      'The value is treated as a column reference',
      'The value is automatically lifted by Quill\'s macro',
    ],
    correctAnswer: 0,
    explanation: 'In Quill, non-lifted Scala values in quote blocks are treated as compile-time constants and inlined into the SQL literal. This is safe for truly constant values but dangerous for user input — always use `lift` for runtime values.',
    codeSnippet: `val ADMIN_ROLE = "admin"  // Scala constant

// Inlined as literal (safe for constants):
val q1 = quote { query[User].filter(_.role == ADMIN_ROLE) }
// SQL: SELECT ... WHERE role = 'admin'

// MUST use lift for runtime/user input:
val userInput: String = getFromRequest()
val q2 = quote { query[User].filter(_.name == lift(userInput)) }
// SQL: SELECT ... WHERE name = ?`,
    tags: ['quill', 'lift', 'inlining', 'sql-injection', 'compile-time'],
  },
];

export default questions;
