import { Question } from '@/types/question';

const questions: Question[] = [
  {
    id: 'scala-db-l2-001',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'How do you perform an upsert (insert or update) in Slick for PostgreSQL?',
    options: [
      'Using insertOrUpdate method on the TableQuery',
      'Using upsert method on the TableQuery',
      'Using merge method on the TableQuery',
      'Using save method on the TableQuery',
    ],
    correctAnswer: 0,
    explanation: 'Slick provides `insertOrUpdate` which generates an INSERT ... ON CONFLICT DO UPDATE statement for PostgreSQL (and equivalent for other databases).',
    codeSnippet: `val upsertAction: DBIO[Int] =
  users.insertOrUpdate(User(1, "Alice", "alice@example.com"))
db.run(upsertAction)`,
    tags: ['slick', 'upsert', 'insert-or-update'],
  },
  {
    id: 'scala-db-l2-002',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'How do you update specific columns in Slick without fetching the full row?',
    options: [
      'query.map(_.column).update(newValue)',
      'query.set(_.column, newValue)',
      'query.update(_.column -> newValue)',
      'query.modify(r => r.copy(column = newValue))',
    ],
    correctAnswer: 0,
    explanation: 'In Slick, you can update specific columns by mapping to them and calling `.update`. This generates an efficient UPDATE SET col = val WHERE ... SQL.',
    codeSnippet: `val updateAction: DBIO[Int] =
  users.filter(_.id === 1).map(_.email).update("new@example.com")`,
    tags: ['slick', 'update', 'partial'],
  },
  {
    id: 'scala-db-l2-003',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'What does `returning` do in Slick insert operations?',
    options: [
      'Returns specified column values (e.g., auto-generated IDs) after insert',
      'Returns the inserted row count as a Long instead of Int',
      'Causes the insert to return a Boolean indicating success',
      'Returns a compiled query for repeated inserts',
    ],
    correctAnswer: 0,
    explanation: '`returning` allows you to get back column values generated by the database (like auto-increment IDs) after an INSERT. It generates INSERT ... RETURNING.',
    codeSnippet: `val insertWithId =
  (users returning users.map(_.id)) += User(0, "Alice", "alice@example.com")
val newId: Future[Int] = db.run(insertWithId)`,
    tags: ['slick', 'returning', 'insert', 'auto-increment'],
  },
  {
    id: 'scala-db-l2-004',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'What is a "compiled query" in Slick and why is it useful?',
    options: [
      'A query that is compiled once and cached to avoid repeated query translation overhead',
      'A query that is validated against the database schema at compile time',
      'A query that uses native SQL instead of Slick\'s lifted embedding',
      'A query stored as a PostgreSQL prepared statement on the server',
    ],
    correctAnswer: 0,
    explanation: 'Slick compiled queries (Compiled) translate the query AST to SQL once and cache the result, saving overhead on repeated executions with different parameters.',
    codeSnippet: `val byId = Compiled((id: Rep[Int]) => users.filter(_.id === id))
val result: Future[Option[User]] = db.run(byId(42).result.headOption)`,
    tags: ['slick', 'compiled-query', 'performance'],
  },
  {
    id: 'scala-db-l2-005',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'How does Slick handle `Option[T]` columns (nullable columns)?',
    options: [
      'Nullable columns are mapped to Option[T]; None maps to NULL',
      'Nullable columns are not supported; use a sentinel value instead',
      'Nullable columns are mapped to T with a default value when NULL',
      'Nullable columns must be handled with a custom ColumnMapper',
    ],
    correctAnswer: 0,
    explanation: 'In Slick, nullable columns are typed as Option[T]. None becomes NULL in SQL and vice versa. Filtering on nullable columns uses isDefined, isEmpty, or === Some(value).',
    codeSnippet: `def middleName = column[Option[String]]("middle_name")

// Filtering nullable columns:
users.filter(_.middleName.isDefined)
users.filter(_.middleName === "Marie".bind)`,
    tags: ['slick', 'nullable', 'option'],
  },
  {
    id: 'scala-db-l2-006',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'How do you perform aggregation (e.g., COUNT, SUM) in Slick?',
    options: [
      'Using .length, .sum, .avg, .min, .max on query columns',
      'Using .aggregate(COUNT) with a column reference',
      'Using .groupAndCount on a query',
      'Using sql"SELECT COUNT(*) FROM ..." raw SQL only',
    ],
    correctAnswer: 0,
    explanation: 'Slick provides aggregate functions as methods: `.length` (COUNT), `.sum`, `.avg`, `.min`, `.max`. They return nullable types (Option) since aggregations can return NULL.',
    codeSnippet: `val countAction: DBIO[Int] = users.length.result
val totalBalance: DBIO[Option[Double]] = accounts.map(_.balance).sum.result`,
    tags: ['slick', 'aggregation', 'count', 'sum'],
  },
  {
    id: 'scala-db-l2-007',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'In Slick, what is the difference between `.join` and `.joinLeft`?',
    options: [
      '.join is INNER JOIN; .joinLeft is LEFT OUTER JOIN, making the right side Option[T]',
      '.join is LEFT JOIN; .joinLeft is RIGHT JOIN',
      '.join returns tuples; .joinLeft returns Either types',
      '.join is for same-table joins; .joinLeft is for cross-table joins',
    ],
    correctAnswer: 0,
    explanation: 'Slick\'s `.join` generates an INNER JOIN. `.joinLeft` generates a LEFT OUTER JOIN, making the right-side columns Option[T] since they may be NULL.',
    codeSnippet: `val q = users.joinLeft(orders).on(_.id === _.userId)
// Result type: Query[(UsersTable, Rep[Option[OrdersTable]]), ...]`,
    tags: ['slick', 'join', 'left-join'],
  },
  {
    id: 'scala-db-l2-008',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Doobie',
    question: 'How do you perform batch inserts efficiently in Doobie?',
    options: [
      'Using Update[A].updateMany(values) with a List of values',
      'Calling .run multiple times in a for-comprehension',
      'Using sql"INSERT INTO ... VALUES ...".updateBatch',
      'Using BatchExecutor.execute(list)',
    ],
    correctAnswer: 0,
    explanation: 'Doobie\'s `Update[A]` combined with `.updateMany(values)` performs an efficient batch insert using JDBC batch execution under the hood.',
    codeSnippet: `val insertUser = Update[User]("INSERT INTO users (id, name) VALUES (?, ?)")
val batchAction: ConnectionIO[Int] =
  insertUser.updateMany(List(User(1, "Alice"), User(2, "Bob")))`,
    tags: ['doobie', 'batch', 'update-many'],
  },
  {
    id: 'scala-db-l2-009',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Doobie',
    question: 'What does `withGeneratedKeys` do in Doobie?',
    options: [
      'Returns a stream of generated key values (like auto-increment IDs) after an insert',
      'Generates random primary keys for inserted rows',
      'Returns the SQL statement with generated key placeholders',
      'Configures JDBC to use server-generated UUIDs',
    ],
    correctAnswer: 0,
    explanation: '`withGeneratedKeys` in Doobie returns an fs2.Stream of generated column values (typically auto-increment IDs) after executing an INSERT statement.',
    codeSnippet: `val insert = Update[String]("INSERT INTO users (name) VALUES (?)")
val ids: fs2.Stream[ConnectionIO, Int] =
  insert.withGeneratedKeys[Int]("id")("Alice")`,
    tags: ['doobie', 'generated-keys', 'insert'],
  },
  {
    id: 'scala-db-l2-010',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Doobie',
    question: 'In Doobie, how do you handle optional WHERE conditions (dynamic queries)?',
    options: [
      'Using Fragment composition with Option.fold or whereAndOpt',
      'Using if-else to choose between different sql"..." blocks',
      'Using Dynamic.where(conditions: _*)',
      'Dynamic queries are not possible in Doobie',
    ],
    correctAnswer: 0,
    explanation: 'Doobie Fragments can be composed dynamically. `Fragments.whereAndOpt` takes Option[Fragment] values and only includes non-None fragments in the WHERE clause.',
    codeSnippet: `def search(name: Option[String], age: Option[Int]): ConnectionIO[List[User]] = {
  val conditions = List(
    name.map(n => fr"name = $n"),
    age.map(a => fr"age = $a")
  )
  val query = fr"SELECT * FROM users" ++ Fragments.whereAndOpt(conditions: _*)
  query.query[User].to[List]
}`,
    tags: ['doobie', 'fragments', 'dynamic-query'],
  },
  {
    id: 'scala-db-l2-011',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Doobie',
    question: 'How do you map a tuple from a Doobie query into a case class?',
    options: [
      'Use .query[(Int, String)].map { case (id, name) => User(id, name) } or derive Read[User] automatically',
      'Use .query[User] only after adding @ReadDerive annotation',
      'Use .queryAs[User] instead of .query',
      'Doobie always requires manual mapping with .map',
    ],
    correctAnswer: 0,
    explanation: 'Doobie can automatically derive Read[User] for case classes (when all fields have Read instances). Alternatively, you can query a tuple and map explicitly.',
    codeSnippet: `// Automatic derivation (preferred):
val q = sql"SELECT id, name FROM users".query[User].to[List]

// Manual mapping:
val q2 = sql"SELECT id, name FROM users"
  .query[(Int, String)]
  .map { case (id, name) => User(id, name) }
  .to[List]`,
    tags: ['doobie', 'read', 'case-class', 'mapping'],
  },
  {
    id: 'scala-db-l2-012',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Doobie',
    question: 'What does `Transactor.fromDataSource` provide over `fromDriverManager`?',
    options: [
      'It uses an existing DataSource (like HikariCP) instead of creating new connections, enabling connection pooling',
      'It provides better error messages for SQL exceptions',
      'It enables automatic schema migration on startup',
      'It supports multiple databases simultaneously',
    ],
    correctAnswer: 0,
    explanation: '`Transactor.fromDataSource` wraps an existing DataSource (e.g., HikariCP), enabling connection pooling. `fromDriverManager` creates a new connection each time, which is only suitable for testing.',
    codeSnippet: `val ds: HikariDataSource = createHikariDataSource()
val xa = Transactor.fromDataSource[IO](ds, connectEC)`,
    tags: ['doobie', 'transactor', 'datasource', 'connection-pooling'],
  },
  {
    id: 'scala-db-l2-013',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'transactions',
    question: 'What are the four standard SQL transaction isolation levels?',
    options: [
      'READ UNCOMMITTED, READ COMMITTED, REPEATABLE READ, SERIALIZABLE',
      'READ ONLY, READ WRITE, SNAPSHOT, SERIALIZABLE',
      'COMMITTED, REPEATABLE, PHANTOM-FREE, SERIALIZABLE',
      'BASIC, STANDARD, ADVANCED, STRICT',
    ],
    correctAnswer: 0,
    explanation: 'SQL defines four isolation levels: READ UNCOMMITTED (lowest), READ COMMITTED, REPEATABLE READ, and SERIALIZABLE (highest). Higher levels prevent more anomalies but may reduce concurrency.',
    tags: ['transactions', 'isolation-levels', 'sql'],
  },
  {
    id: 'scala-db-l2-014',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'transactions',
    question: 'What is a "phantom read" in database transactions?',
    options: [
      'A transaction re-executes a query and finds new rows inserted by another committed transaction',
      'A transaction reads data that was deleted by another transaction',
      'A transaction reads uncommitted data from another transaction',
      'A transaction reads the same row twice and gets different values',
    ],
    correctAnswer: 0,
    explanation: 'A phantom read occurs when a transaction re-runs a range query and finds new rows that were inserted by another committed transaction. SERIALIZABLE isolation prevents phantom reads.',
    tags: ['transactions', 'phantom-read', 'isolation'],
  },
  {
    id: 'scala-db-l2-015',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'transactions',
    question: 'How do you set the transaction isolation level in Doobie?',
    options: [
      'Using HC.setTransactionIsolation(level) in the ConnectionIO program',
      'By configuring it in the Transactor constructor',
      'By setting the isolation level in the SQL query itself',
      'Doobie always uses the database default isolation level',
    ],
    correctAnswer: 0,
    explanation: 'In Doobie, `HC.setTransactionIsolation` is a ConnectionIO operation that sets the isolation level on the JDBC connection before executing queries.',
    codeSnippet: `import java.sql.Connection
import doobie.free.connection.{HC, setTransactionIsolation}

val program = for {
  _ <- HC.setTransactionIsolation(Connection.TRANSACTION_SERIALIZABLE)
  result <- sql"SELECT * FROM accounts".query[Account].to[List]
} yield result`,
    tags: ['doobie', 'transactions', 'isolation-level'],
  },
  {
    id: 'scala-db-l2-016',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'connection pooling',
    question: 'What is the "connection timeout" in HikariCP?',
    options: [
      'The maximum time to wait for a connection from the pool before throwing an exception',
      'The maximum time a connection can be held open before being forcibly closed',
      'The maximum time a query can run before being cancelled',
      'The time between connection health checks',
    ],
    correctAnswer: 0,
    explanation: '`connectionTimeout` in HikariCP is how long a client will wait for a pool connection before a SQLException is thrown. Default is 30 seconds.',
    tags: ['connection-pooling', 'hikaricp', 'timeout'],
  },
  {
    id: 'scala-db-l2-017',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'connection pooling',
    question: 'What is HikariCP\'s `keepaliveTime` property used for?',
    options: [
      'To periodically send a heartbeat query to prevent idle connections from being closed by the database or firewall',
      'To set the maximum lifetime of a connection in the pool',
      'To configure the health check interval for pool monitoring',
      'To set the interval between pool size adjustments',
    ],
    correctAnswer: 0,
    explanation: 'keepaliveTime controls how often HikariCP sends keepalive queries on idle connections to prevent them from being killed by database servers or network firewalls.',
    tags: ['connection-pooling', 'hikaricp', 'keepalive'],
  },
  {
    id: 'scala-db-l2-018',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'connection pooling',
    question: 'What is the recommended pool size formula for CPU-bound PostgreSQL workloads according to HikariCP?',
    options: [
      'pool_size = (number_of_cores * 2) + number_of_spindle_disks',
      'pool_size = number_of_threads_in_application',
      'pool_size = max_connections / number_of_application_instances',
      'pool_size = 100 (fixed default)',
    ],
    correctAnswer: 0,
    explanation: 'The HikariCP/PgBouncer recommendation for PostgreSQL is: connections = (cpu_cores * 2) + effective_spindle_count. A pool that\'s too large actually hurts performance.',
    tags: ['connection-pooling', 'hikaricp', 'pool-sizing'],
  },
  {
    id: 'scala-db-l2-019',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'migrations',
    question: 'How can you integrate Flyway into a Scala application that uses Cats Effect?',
    options: [
      'Wrap flyway.migrate() in IO.blocking to run it at application startup',
      'Use the Flyway IO module which provides a pure FP interface',
      'Flyway requires a separate process and cannot be embedded in Cats Effect apps',
      'Use flyway.migrateAsync() which returns a CompletableFuture',
    ],
    correctAnswer: 0,
    explanation: 'Since Flyway\'s migrate() is a blocking Java call, you wrap it in IO.blocking (or IO.delay) to lift it into the IO context safely.',
    codeSnippet: `def migrate(config: FlywayConfig): IO[MigrateResult] =
  IO.blocking {
    Flyway.configure()
      .dataSource(config.url, config.user, config.pass)
      .load()
      .migrate()
  }`,
    tags: ['flyway', 'migrations', 'cats-effect', 'io-blocking'],
  },
  {
    id: 'scala-db-l2-020',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'migrations',
    question: 'What does `flyway.validate()` do?',
    options: [
      'Checks that the applied migrations match the migration files (checksums), failing if any mismatch is found',
      'Validates the SQL syntax of all pending migration files',
      'Verifies database connectivity before running migrations',
      'Ensures all tables referenced in migrations exist',
    ],
    correctAnswer: 0,
    explanation: 'flyway.validate() compares checksums of applied migrations against the current files. It fails if migrations were modified after being applied, detecting unintended changes.',
    tags: ['flyway', 'migrations', 'validate'],
  },
  {
    id: 'scala-db-l2-021',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'migrations',
    question: 'What is a "baseline" migration in Flyway?',
    options: [
      'A migration that marks an existing database as the starting point, so Flyway ignores older migration versions',
      'The first migration file created in a project',
      'A migration that creates the flyway_schema_history table',
      'A migration that can be rolled back automatically',
    ],
    correctAnswer: 0,
    explanation: 'flyway.baseline() is used to start using Flyway on an existing database. It marks the current state as the baseline, so Flyway only applies newer migrations.',
    tags: ['flyway', 'migrations', 'baseline'],
  },
  {
    id: 'scala-db-l2-022',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Quill',
    question: 'In Quill, how do you insert a record and return its generated ID?',
    options: [
      'Using ctx.run(query[T].insertValue(t).returningGenerated(_.id))',
      'Using ctx.insert(t).withId',
      'Using ctx.run(query[T].insert(t)).id',
      'Using InsertReturning.run(ctx, t)',
    ],
    correctAnswer: 0,
    explanation: 'Quill\'s `.returningGenerated(_.id)` on an insert action generates INSERT ... RETURNING id SQL, returning the auto-generated primary key.',
    codeSnippet: `val newId: Long = ctx.run(
  query[User].insertValue(User(0, "Alice")).returningGenerated(_.id)
)`,
    tags: ['quill', 'insert', 'returning', 'generated-id'],
  },
  {
    id: 'scala-db-l2-023',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Quill',
    question: 'In Quill, how do you perform a batch insert?',
    options: [
      'ctx.run(liftQuery(list).foreach(e => query[T].insertValue(e)))',
      'ctx.runBatch(list, query[T].insertValue)',
      'ctx.run(query[T].insertAll(list))',
      'ctx.batch(list).insert',
    ],
    correctAnswer: 0,
    explanation: 'Quill batch operations use `liftQuery(list).foreach(...)`. This generates a single JDBC batch prepared statement for efficient bulk insertion.',
    codeSnippet: `val users = List(User(0, "Alice"), User(0, "Bob"))
ctx.run(liftQuery(users).foreach(u => query[User].insertValue(u)))`,
    tags: ['quill', 'batch', 'insert'],
  },
  {
    id: 'scala-db-l2-024',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Quill',
    question: 'In Quill, how do you perform a join between two tables?',
    options: [
      'Using for-comprehension inside a quote block',
      'Using query[A].join(query[B])',
      'Using join(query[A], query[B]).on(condition)',
      'Using Query.joinWith(query[A], query[B])',
    ],
    correctAnswer: 0,
    explanation: 'Quill supports joins using for-comprehension syntax inside quote blocks, similar to Slick.',
    codeSnippet: `val q = quote {
  for {
    u <- query[User]
    o <- query[Order] if o.userId == u.id
  } yield (u, o)
}
ctx.run(q)`,
    tags: ['quill', 'join', 'query'],
  },
  {
    id: 'scala-db-l2-025',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Skunk',
    question: 'In Skunk, how do you prepare a query for repeated execution?',
    options: [
      'Using session.prepare(query) which returns a Resource[IO, PreparedQuery[...]]',
      'Using session.compile(query)',
      'Using PreparedStatement.create(session, query)',
      'Skunk always prepares queries automatically',
    ],
    correctAnswer: 0,
    explanation: 'Skunk\'s session.prepare(query) creates a server-side prepared statement. It returns a Resource that manages the statement lifecycle on the PostgreSQL server.',
    codeSnippet: `val userQuery: Query[Int, User] =
  sql"SELECT id, name FROM users WHERE id = $int4"
    .query(int4 ~ varchar).map { case id ~ name => User(id, name) }

session.prepare(userQuery).use { pq =>
  pq.unique(42)
}`,
    tags: ['skunk', 'prepared-query', 'session'],
  },
  {
    id: 'scala-db-l2-026',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Skunk',
    question: 'How do you run a transaction in Skunk?',
    options: [
      'Using session.transaction which provides a Resource[IO, Transaction[IO]]',
      'Using session.begin()/session.commit()',
      'Using Transaction.run(session)(program)',
      'Wrapping commands in session.inTransaction { ... }',
    ],
    correctAnswer: 0,
    explanation: 'Skunk provides session.transaction as a Resource that begins a transaction on acquisition and commits (or rolls back on error) on release.',
    codeSnippet: `session.transaction.use { tx =>
  for {
    _ <- session.execute(insertCmd)(data1)
    _ <- session.execute(insertCmd)(data2)
  } yield ()
}`,
    tags: ['skunk', 'transactions', 'resource'],
  },
  {
    id: 'scala-db-l2-027',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Skunk',
    question: 'In Skunk, what does the `~` operator do with Codecs?',
    options: [
      'It combines two Codecs into a product Codec, mapping to/from a tuple',
      'It creates an optional (nullable) version of a Codec',
      'It applies a transformation function to a Codec',
      'It marks a Codec as non-nullable',
    ],
    correctAnswer: 0,
    explanation: 'The `~` operator on Skunk Codecs creates a product Codec. `int4 ~ varchar` produces a `Codec[Int ~ String]` (where `~` is also a tuple type alias in Skunk).',
    codeSnippet: `val codec: Codec[Int ~ String] = int4 ~ varchar
// Used in query to decode two columns at once`,
    tags: ['skunk', 'codec', 'product', 'tilde'],
  },
  {
    id: 'scala-db-l2-028',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'streaming queries',
    question: 'In Doobie, how do you control the fetch size when streaming a large result set?',
    options: [
      'Using .streamWithChunkSize(n) or setting fetch size on the PreparedStatement via HC',
      'Using .stream(fetchSize = n)',
      'Using Transactor.withFetchSize(n)',
      'Fetch size cannot be controlled in Doobie',
    ],
    correctAnswer: 0,
    explanation: 'Doobie\'s `.streamWithChunkSize(n)` controls how many rows are fetched per JDBC round trip when streaming. Alternatively, you can configure it via the connection\'s PreparedStatement.',
    codeSnippet: `val stream: fs2.Stream[ConnectionIO, User] =
  sql"SELECT * FROM large_table"
    .query[User]
    .streamWithChunkSize(500)`,
    tags: ['doobie', 'streaming', 'fetch-size'],
  },
  {
    id: 'scala-db-l2-029',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'streaming queries',
    question: 'When streaming Slick results, what must you do to ensure the cursor stays open throughout processing?',
    options: [
      'Keep the database session open during stream consumption; do not close db until done',
      'Set autoCloseResultSet = false on the Slick profile',
      'Use db.stream instead of db.run',
      'Wrap the stream in a transaction to pin the cursor',
    ],
    correctAnswer: 0,
    explanation: 'Slick\'s DatabasePublisher requires the database session to remain open while consuming the stream. Closing the database or connection prematurely will break the stream.',
    tags: ['slick', 'streaming', 'cursor', 'session'],
  },
  {
    id: 'scala-db-l2-030',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'JDBC interop',
    question: 'What is the `DataSource` interface in JDBC and why is it preferred over `DriverManager`?',
    options: [
      'DataSource is a factory for connections that supports connection pooling, unlike DriverManager which creates new connections each time',
      'DataSource provides async JDBC operations; DriverManager is synchronous only',
      'DataSource is thread-safe; DriverManager is not thread-safe',
      'DataSource supports multiple databases simultaneously; DriverManager supports only one',
    ],
    correctAnswer: 0,
    explanation: 'DataSource is a JDBC interface that abstracts connection creation. Connection pools implement DataSource, allowing applications to get pooled connections transparently.',
    tags: ['jdbc', 'datasource', 'connection-pooling'],
  },
  {
    id: 'scala-db-l2-031',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'JDBC interop',
    question: 'What is a JDBC batch statement and when should you use it?',
    options: [
      'A batch groups multiple SQL statements into one round trip, used for bulk inserts/updates to reduce network overhead',
      'A batch statement runs multiple queries in parallel on different connections',
      'A batch is a stored procedure that can execute multiple SQL statements',
      'A batch is used exclusively for reading large datasets from the database',
    ],
    correctAnswer: 0,
    explanation: 'JDBC batching (addBatch/executeBatch) groups DML statements into a single network round trip, dramatically improving bulk operation performance.',
    codeSnippet: `val stmt = conn.prepareStatement("INSERT INTO users (name) VALUES (?)")
List("Alice", "Bob", "Charlie").foreach { name =>
  stmt.setString(1, name)
  stmt.addBatch()
}
val counts = stmt.executeBatch()`,
    tags: ['jdbc', 'batch', 'performance'],
  },
  {
    id: 'scala-db-l2-032',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'JSON codecs for DB',
    question: 'How do you define a custom Doobie Meta instance for encoding/decoding a case class as JSON?',
    options: [
      'Using Meta[String].timap(decode, encode) with a JSON library',
      'By extending the JsonMeta[A] abstract class',
      'By annotating the case class with @DoobieMeta',
      'Meta instances for custom types must be created by Doobie core',
    ],
    correctAnswer: 0,
    explanation: 'You can create a Meta[A] by transforming a String Meta using timap (total bidirectional map), encoding A to String (JSON) and decoding String to A.',
    codeSnippet: `import io.circe.syntax._
import io.circe.parser._

implicit val metaProfile: Meta[UserProfile] =
  Meta[String].timap(
    str => decode[UserProfile](str).getOrElse(throw new Exception("decode failed")),
    profile => profile.asJson.noSpaces
  )`,
    tags: ['doobie', 'meta', 'json', 'circe', 'custom'],
  },
  {
    id: 'scala-db-l2-033',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'JSON codecs for DB',
    question: 'In Slick with slick-pg, how do you query a JSONB field for a specific key?',
    options: [
      'Using the `+>` or `->` operators provided by PgJsonSupport',
      'Using raw SQL with sql"column->\'key\'"',
      'Using column.getKey("key") method',
      'JSON querying is not supported in Slick',
    ],
    correctAnswer: 0,
    explanation: 'slick-pg\'s PgJsonSupport provides PostgreSQL JSON operators like `->` (get JSON object field as JSON) and `->>` (get as text). These translate to PostgreSQL\'s JSON operators.',
    tags: ['slick', 'slick-pg', 'jsonb', 'operators'],
  },
  {
    id: 'scala-db-l2-034',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'How do you use `groupBy` in Slick?',
    options: [
      '.groupBy(_.column).map { case (key, group) => (key, group.length) }',
      '.groupBy(_.column).aggregate(COUNT)',
      '.partition(_.column).map(_.size)',
      '.group(_.column).count',
    ],
    correctAnswer: 0,
    explanation: 'Slick\'s `.groupBy` works like SQL GROUP BY. You provide a key function, and then map over the (key, group) pair, applying aggregate functions to the group.',
    codeSnippet: `val countByDept: DBIO[Seq[(String, Int)]] =
  employees
    .groupBy(_.department)
    .map { case (dept, group) => (dept, group.length) }
    .result`,
    tags: ['slick', 'group-by', 'aggregation'],
  },
  {
    id: 'scala-db-l2-035',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'What is a `MappedColumnType` in Slick?',
    options: [
      'A custom bidirectional mapping between a Scala type and a database column type',
      'A column type that applies a function before each query',
      'A type alias for nullable columns',
      'A column constraint that maps to a database check constraint',
    ],
    correctAnswer: 0,
    explanation: 'MappedColumnType (via MappedJdbcType.base) allows mapping custom Scala types (like enums, value classes) to basic SQL types for storage.',
    codeSnippet: `sealed trait Status
case object Active extends Status
case object Inactive extends Status

implicit val statusMapper = MappedColumnType.base[Status, String](
  s => s.toString,
  s => if (s == "Active") Active else Inactive
)

def status = column[Status]("status")`,
    tags: ['slick', 'mapped-column-type', 'custom-type'],
  },
  {
    id: 'scala-db-l2-036',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Doobie',
    question: 'What is the purpose of `Check` in Doobie (from doobie-specs2 or doobie-scalatest)?',
    options: [
      'It validates that a Doobie query\'s parameter types and result types match the actual database schema',
      'It runs unit tests on SQL query logic',
      'It validates that all required imports are present',
      'It checks database connectivity before running tests',
    ],
    correctAnswer: 0,
    explanation: 'Doobie\'s `check` utility (from test modules) connects to a real database and verifies that a query\'s parameter/result types are compatible with the actual column types — a powerful correctness guarantee.',
    codeSnippet: `class DatabaseSpec extends AnyFunSuite with IOChecker {
  val transactor = // ...
  test("select users query") { check(sql"SELECT id, name FROM users".query[User]) }
}`,
    tags: ['doobie', 'check', 'testing', 'type-checking'],
  },
  {
    id: 'scala-db-l2-037',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Skunk',
    question: 'In Skunk, how do you decode a nullable column (Option type)?',
    options: [
      'Using codec.opt to create an optional Codec',
      'Using Option[codec] syntax',
      'Using codec.nullable',
      'Using OptionalCodec(codec)',
    ],
    correctAnswer: 0,
    explanation: 'Skunk\'s `.opt` extension on Codec[A] creates a `Codec[Option[A]]` that handles NULL values in PostgreSQL columns.',
    codeSnippet: `val codec: Codec[Int ~ Option[String]] = int4 ~ varchar.opt
// Decodes a row with a required Int and optional String`,
    tags: ['skunk', 'codec', 'nullable', 'option'],
  },
  {
    id: 'scala-db-l2-038',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Skunk',
    question: 'How does Skunk handle multiple result rows from a query?',
    options: [
      'Using pq.stream(params, chunkSize) which returns an fs2.Stream[IO, A]',
      'Using pq.list(params) which returns IO[List[A]]',
      'Using pq.runAll(params) which returns IO[Vector[A]]',
      'Using pq.execute(params) which returns IO[ResultSet]',
    ],
    correctAnswer: 0,
    explanation: 'Skunk prepared queries produce results as fs2 Streams via `.stream(params, chunkSize)`. For a single result you use `.unique` or `.option`.',
    codeSnippet: `session.prepare(allUsersQuery).use { pq =>
  pq.stream(Void, 64)
    .evalMap(user => IO.println(user))
    .compile.drain
}`,
    tags: ['skunk', 'stream', 'query', 'fs2'],
  },
  {
    id: 'scala-db-l2-039',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'connection pooling',
    question: 'In Cats Effect with Doobie, how do you correctly acquire and release a HikariTransactor?',
    options: [
      'Using HikariTransactor.newHikariTransactor[IO](...) as a Resource[IO, HikariTransactor[IO]]',
      'Using HikariTransactor.apply(...) and manually calling close()',
      'Using HikariTransactor.fromConfig(...) which auto-manages lifecycle',
      'Using cats.effect.IO.bracket to acquire and release',
    ],
    correctAnswer: 0,
    explanation: 'HikariTransactor is created as a Cats Effect Resource, which ensures the connection pool is properly shut down when the application stops.',
    codeSnippet: `HikariTransactor
  .newHikariTransactor[IO](
    "org.postgresql.Driver",
    "jdbc:postgresql://localhost/mydb",
    "user", "pass",
    connectEC
  )
  .use { xa =>
    myApp(xa)
  }`,
    tags: ['doobie', 'hikaricp', 'resource', 'cats-effect'],
  },
  {
    id: 'scala-db-l2-040',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Quill',
    question: 'In Quill, what is the purpose of `implicit val naming: NamingStrategy`?',
    options: [
      'It controls how Scala identifiers are translated to SQL table/column names (e.g., camelCase to snake_case)',
      'It sets the character encoding for SQL strings',
      'It controls how SQL is printed in log messages',
      'It defines the order of columns in INSERT statements',
    ],
    correctAnswer: 0,
    explanation: 'Quill\'s NamingStrategy (e.g., SnakeCase, PluralizedTableNames) controls the conversion between Scala camelCase names and SQL snake_case names automatically.',
    codeSnippet: `val ctx = new PostgresJdbcContext(SnakeCase, "mydb")
// case class UserProfile -> table "user_profiles"
// field firstName -> column "first_name"`,
    tags: ['quill', 'naming-strategy', 'snake-case'],
  },
  {
    id: 'scala-db-l2-041',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Quill',
    question: 'In Quill, how do you perform a LEFT JOIN?',
    options: [
      'Using leftJoin inside a quote block',
      'Using join(...).left in a quote block',
      'Using for { a <- query[A]; b <- query[B].leftJoin } yield (a, b)',
      'Quill only supports INNER JOINs natively',
    ],
    correctAnswer: 0,
    explanation: 'Quill supports `leftJoin` in quote blocks for LEFT OUTER JOINs. The right side becomes an Option type.',
    codeSnippet: `val q = quote {
  query[User].leftJoin(query[Order]).on((u, o) => u.id == o.userId)
}
// Returns List[(User, Option[Order])]`,
    tags: ['quill', 'left-join', 'query'],
  },
  {
    id: 'scala-db-l2-042',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'JDBC interop',
    question: 'How do you call a stored procedure in JDBC?',
    options: [
      'Using conn.prepareCall("{call procedure_name(?, ?)}") which returns a CallableStatement',
      'Using conn.prepareStatement("CALL procedure_name(?, ?)")',
      'Using conn.executeStoredProcedure("procedure_name", params)',
      'Stored procedures cannot be called from JDBC',
    ],
    correctAnswer: 0,
    explanation: 'JDBC uses `CallableStatement` (created via prepareCall) to call stored procedures. The `{call ...}` syntax is database-independent.',
    codeSnippet: `val cs = conn.prepareCall("{call get_user_stats(?, ?)}")
cs.setInt(1, userId)
cs.registerOutParameter(2, Types.INTEGER)
cs.execute()
val result = cs.getInt(2)`,
    tags: ['jdbc', 'stored-procedure', 'callable-statement'],
  },
  {
    id: 'scala-db-l2-043',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'JDBC interop',
    question: 'What does setting `conn.setReadOnly(true)` do in JDBC?',
    options: [
      'Hints to the driver that the connection will only be used for reads, potentially enabling optimizations',
      'Prevents any write operations from executing on this connection',
      'Forces all queries to use read-only replicas',
      'Disables transaction management on the connection',
    ],
    correctAnswer: 0,
    explanation: '`setReadOnly(true)` is a hint to the JDBC driver that the connection will be used for reads only. The driver/database may use this to route to replicas or optimize execution.',
    tags: ['jdbc', 'read-only', 'connection'],
  },
  {
    id: 'scala-db-l2-044',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'streaming queries',
    question: 'In fs2 with Doobie, how do you limit the number of items consumed from a stream?',
    options: [
      '.take(n)',
      '.limit(n)',
      '.first(n)',
      '.head(n)',
    ],
    correctAnswer: 0,
    explanation: 'fs2.Stream\'s `.take(n)` limits the stream to the first n elements. In Doobie, this means only n rows will be fetched from the database cursor.',
    codeSnippet: `val first100: fs2.Stream[ConnectionIO, User] =
  sql"SELECT * FROM users".query[User].stream.take(100)`,
    tags: ['doobie', 'fs2', 'streaming', 'take'],
  },
  {
    id: 'scala-db-l2-045',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'In Slick, how can you run two independent DBIO actions and collect both results?',
    options: [
      'Using DBIO.zip(action1, action2) or for-comprehension',
      'Using DBIO.parallel(action1, action2)',
      'Using Future.zip(db.run(action1), db.run(action2))',
      'DBIO actions can only run sequentially in Slick',
    ],
    correctAnswer: 0,
    explanation: 'DBIO.zip combines two actions into one that returns a tuple of results. Note that Slick DBIO actions are sequential within a session; true parallelism requires separate db.run calls.',
    codeSnippet: `val combined: DBIO[(Seq[User], Seq[Order])] =
  users.result.zip(orders.result)

val result: Future[(Seq[User], Seq[Order])] = db.run(combined)`,
    tags: ['slick', 'dbio', 'zip', 'parallel'],
  },
  {
    id: 'scala-db-l2-046',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'What does `DBIO.fold` do in Slick?',
    options: [
      'Runs a sequence of DBIO actions and folds the results with an accumulator function',
      'Reduces a collection of database rows into a single value in memory',
      'Combines multiple queries into a SQL UNION',
      'Applies a fold/reduce SQL aggregate function',
    ],
    correctAnswer: 0,
    explanation: 'DBIO.fold takes a sequence of DBIO actions and a fold function, executing each action and accumulating results. Useful for chaining dependent operations.',
    tags: ['slick', 'dbio', 'fold'],
  },
  {
    id: 'scala-db-l2-047',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Doobie',
    question: 'In Doobie, what is the Write[A] typeclass?',
    options: [
      'It provides the logic to write/encode a Scala type A into JDBC parameters for queries',
      'It is the dual of Read[A], used for INSERT and UPDATE parameters',
      'Both A and B are correct',
      'It provides serialization to a binary format for streaming',
    ],
    correctAnswer: 2,
    explanation: '`Write[A]` in Doobie provides encoding of Scala type A into JDBC parameters. It is the dual of `Read[A]` and is used when setting parameters in INSERT/UPDATE statements.',
    tags: ['doobie', 'write', 'typeclass'],
  },
  {
    id: 'scala-db-l2-048',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Doobie',
    question: 'How do you run a Doobie `ConnectionIO` in a resource-safe way using Cats Effect?',
    options: [
      'Using .transact(xa) which manages connection acquisition, commit/rollback, and release',
      'Using IO.fromFuture(conn.run())',
      'Using conn.compile.drain',
      'Using xa.run(program)',
    ],
    correctAnswer: 0,
    explanation: '.transact(xa) is the standard way to run a ConnectionIO. The Transactor handles acquiring a connection, running the program, committing or rolling back, and releasing the connection.',
    tags: ['doobie', 'transact', 'cats-effect'],
  },
  {
    id: 'scala-db-l2-049',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'JSON codecs for DB',
    question: 'In Skunk, how do you work with JSON columns in PostgreSQL?',
    options: [
      'Using the skunk-circe module which provides json[A] and jsonb[A] codecs',
      'Using jsonCodec[A] from the core skunk package',
      'Manually converting to/from String with custom Codecs',
      'Skunk does not support JSON columns',
    ],
    correctAnswer: 0,
    explanation: 'The skunk-circe integration provides `json[A]` and `jsonb[A]` Codecs that handle JSON/JSONB PostgreSQL columns using circe for encoding/decoding.',
    codeSnippet: `import skunk.circe.codec.json._
import io.circe.generic.auto._

val profileCodec: Codec[UserProfile] = jsonb[UserProfile]
val query = sql"SELECT profile FROM users WHERE id = $int4".query(profileCodec)`,
    tags: ['skunk', 'json', 'circe', 'postgresql'],
  },
  {
    id: 'scala-db-l2-050',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'migrations',
    question: 'How do you use Flyway with sbt in a Scala project?',
    options: [
      'Using the sbt-flyway plugin which provides sbt tasks like flywayMigrate',
      'By adding a Flyway dependency and calling migrate() in the Main object',
      'By running Flyway from the command line before starting the application',
      'All of the above are valid approaches',
    ],
    correctAnswer: 3,
    explanation: 'Flyway can be integrated via the sbt-flyway plugin (providing sbt tasks), programmatically in application startup code, or via CLI. All three approaches are valid depending on the use case.',
    tags: ['flyway', 'migrations', 'sbt', 'integration'],
  },
  {
    id: 'scala-db-l2-051',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'What is `Slick.profile` (formerly `driver`) and why does it matter?',
    options: [
      'It is the database-specific implementation that determines which SQL dialect is generated',
      'It is a performance profiling tool for Slick queries',
      'It is the configuration for the connection pool',
      'It is the logging configuration for Slick',
    ],
    correctAnswer: 0,
    explanation: 'A Slick profile (like PostgresProfile, MySQLProfile, H2Profile) provides the SQL dialect, type mappings, and DDL generation specific to a database. You import the profile\'s API to write queries.',
    tags: ['slick', 'profile', 'dialect'],
  },
  {
    id: 'scala-db-l2-052',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'How do you use Slick with a polymorphic profile (useful for testing with H2)?',
    options: [
      'Accept a JdbcProfile parameter and import api from the profile instance',
      'Use the TestProfile that automatically detects the environment',
      'Import slick.test.api._ instead of a specific profile',
      'Polymorphic profiles are not supported in Slick',
    ],
    correctAnswer: 0,
    explanation: 'To write code that works with multiple databases (e.g., H2 for tests, PostgreSQL for production), accept a JdbcProfile as a parameter and import its api.',
    codeSnippet: `class UserRepository(val profile: JdbcProfile)(implicit ec: ExecutionContext) {
  import profile.api._

  class UsersTable(tag: Tag) extends Table[User](tag, "users") { ... }
  val users = TableQuery[UsersTable]
}`,
    tags: ['slick', 'profile', 'testing', 'polymorphic'],
  },
  {
    id: 'scala-db-l2-053',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'JDBC interop',
    question: 'What is a connection leak in the context of JDBC and connection pooling?',
    options: [
      'When a connection obtained from the pool is not returned, eventually exhausting the pool',
      'When database credentials are exposed in log files',
      'When a connection transmits data to unintended endpoints',
      'When too many connections are opened simultaneously exceeding the database limit',
    ],
    correctAnswer: 0,
    explanation: 'A connection leak occurs when code obtains a JDBC connection but does not close/return it. Over time the pool runs out of available connections, causing the application to hang.',
    tags: ['jdbc', 'connection-leak', 'connection-pooling'],
  },
  {
    id: 'scala-db-l2-054',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Quill',
    question: 'In Quill, how do you filter with an optional parameter?',
    options: [
      'Using Option.fold to conditionally apply a filter inside the quote block',
      'Using filterOpt directly in Quill',
      'Using if (param.isDefined) quote { query[T].filter(...) } else quote { query[T] }',
      'Both A and C are valid approaches',
    ],
    correctAnswer: 3,
    explanation: 'In Quill, dynamic optional filtering can be done by composing quoted queries with Option.fold or by branching outside the quote block to select different queries.',
    codeSnippet: `def findUsers(name: Option[String]) = {
  val base = quote(query[User])
  val filtered = name.fold(base)(n => quote(base.filter(_.name == lift(n))))
  ctx.run(filtered)
}`,
    tags: ['quill', 'optional-filter', 'dynamic-query'],
  },
  {
    id: 'scala-db-l2-055',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'transactions',
    question: 'What is optimistic locking in database transactions?',
    options: [
      'A strategy where conflicts are detected at commit time using version numbers or timestamps, rather than locking rows upfront',
      'A locking strategy that always assumes no conflicts and never acquires locks',
      'A strategy that uses database locks but releases them immediately after each operation',
      'A type of lock that only applies to read operations, not writes',
    ],
    correctAnswer: 0,
    explanation: 'Optimistic locking assumes conflicts are rare. Rows include a version/timestamp. Before committing, the system checks if the version changed (concurrent update). If so, the transaction fails and is retried.',
    tags: ['transactions', 'optimistic-locking', 'concurrency'],
  },
  {
    id: 'scala-db-l2-056',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Doobie',
    question: 'In Doobie, what does `HC.execute(sql)` do?',
    options: [
      'Executes a raw SQL string directly using JDBC, returning a ConnectionIO[Boolean]',
      'Executes a typed Doobie query',
      'Provides async execution of a query',
      'Creates a HikariCP connection from a SQL URL',
    ],
    correctAnswer: 0,
    explanation: '`HC.execute` is part of Doobie\'s low-level JDBC free monad API. It executes arbitrary SQL and is useful for DDL statements or operations not covered by the high-level API.',
    tags: ['doobie', 'hc', 'raw-sql', 'low-level'],
  },
  {
    id: 'scala-db-l2-057',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'streaming queries',
    question: 'What is backpressure in the context of streaming database queries?',
    options: [
      'A mechanism where the consumer signals to the producer how fast it can process data, preventing buffer overflow',
      'The increased load on the database when multiple streams read simultaneously',
      'The delay caused by network latency between the database and application',
      'A feature where the database pushes data to the client automatically',
    ],
    correctAnswer: 0,
    explanation: 'Backpressure in reactive streaming allows a slow consumer to signal to the database cursor to slow down row fetching, preventing memory overflow when processing faster than consuming.',
    tags: ['streaming', 'backpressure', 'reactive-streams'],
  },
  {
    id: 'scala-db-l2-058',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'What is the `O.Unique` column option in Slick?',
    options: [
      'It creates a unique constraint on the column',
      'It marks the column as a primary key',
      'It ensures the column value is not null',
      'It creates a unique index but not a constraint',
    ],
    correctAnswer: 0,
    explanation: '`O.Unique` in Slick creates a UNIQUE constraint on the column, ensuring no two rows have the same value in that column.',
    codeSnippet: `def email = column[String]("email", O.Unique)`,
    tags: ['slick', 'unique', 'constraint'],
  },
  {
    id: 'scala-db-l2-059',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Skunk',
    question: 'In Skunk, what is a `Channel` used for?',
    options: [
      'PostgreSQL LISTEN/NOTIFY for pub-sub messaging between database sessions',
      'A channel for multiplexing multiple queries on one connection',
      'An internal buffer for large query results',
      'A type-safe wrapper around PostgreSQL sequences',
    ],
    correctAnswer: 0,
    explanation: 'Skunk\'s Channel provides a type-safe interface to PostgreSQL\'s LISTEN/NOTIFY mechanism, enabling pub-sub messaging between database clients.',
    codeSnippet: `session.channel(id"my_channel").use { ch =>
  ch.listen(128).take(10).compile.toList
}`,
    tags: ['skunk', 'channel', 'listen-notify', 'pubsub'],
  },
  {
    id: 'scala-db-l2-060',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'JSON codecs for DB',
    question: 'When storing JSON in PostgreSQL, what is the advantage of JSONB over JSON?',
    options: [
      'JSONB stores data in a parsed binary format that supports indexing and faster operations; JSON stores raw text',
      'JSONB supports nested arrays; JSON does not',
      'JSONB is more compact than JSON for large documents',
      'JSONB allows dynamic schema validation; JSON does not',
    ],
    correctAnswer: 0,
    explanation: 'JSONB parses and stores JSON as binary, enabling GIN indexing, @> (containment) operators, and faster field extraction. JSON stores the exact text and must parse on every operation.',
    tags: ['postgresql', 'jsonb', 'json', 'comparison'],
  },
  {
    id: 'scala-db-l2-061',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'connection pooling',
    question: 'What does `leakDetectionThreshold` do in HikariCP?',
    options: [
      'Logs a warning if a connection is held longer than the specified time, helping detect connection leaks',
      'Sets the time before idle connections are closed',
      'Configures the maximum lifetime of a connection',
      'Sets the interval for connection health checks',
    ],
    correctAnswer: 0,
    explanation: '`leakDetectionThreshold` in HikariCP helps detect connection leaks by logging a stack trace when a connection is held longer than the configured duration (e.g., 10 seconds).',
    tags: ['connection-pooling', 'hikaricp', 'leak-detection'],
  },
  {
    id: 'scala-db-l2-062',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'How does Slick handle the N+1 query problem?',
    options: [
      'By using joins instead of nested queries, composing queries before execution',
      'Slick automatically detects and batches related queries',
      'By enabling lazy loading of related entities',
      'Slick has no special handling; the developer must be aware of it',
    ],
    correctAnswer: 0,
    explanation: 'In Slick, you address N+1 by composing queries with joins before executing. Since Slick queries are data structures, you can build complex joined queries and execute them as a single SQL statement.',
    tags: ['slick', 'n+1', 'performance', 'join'],
  },
  {
    id: 'scala-db-l2-063',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'migrations',
    question: 'What does the `flyway.repair()` command do?',
    options: [
      'Removes failed migration entries from the schema history table and re-aligns checksums',
      'Rolls back the last applied migration',
      'Recreates the flyway_schema_history table',
      'Repairs syntax errors in migration SQL files',
    ],
    correctAnswer: 0,
    explanation: 'flyway.repair() removes failed migration entries from the history table and re-aligns checksums of applied migrations to match the current files (useful after manual repairs).',
    tags: ['flyway', 'migrations', 'repair'],
  },
  {
    id: 'scala-db-l2-064',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Doobie',
    question: 'In Doobie, how do you log all SQL queries for debugging?',
    options: [
      'Using the LogHandler typeclass when building queries, e.g., sql"...".queryWithLogHandler[T](LogHandler.jdkLogHandler)',
      'Setting doobie.log.level=DEBUG in application.conf',
      'Using DoobieLogger.enable(true) before queries',
      'Doobie does not support SQL query logging',
    ],
    correctAnswer: 0,
    explanation: 'Doobie supports SQL logging via `LogHandler`. You pass a LogHandler to queries/updates (or use the implicit default) to log SQL, parameters, and timing.',
    codeSnippet: `import doobie.util.log.LogHandler

val lh = LogHandler.jdkLogHandler
val q = sql"SELECT * FROM users".queryWithLogHandler[User](lh).to[List]`,
    tags: ['doobie', 'logging', 'debugging'],
  },
  {
    id: 'scala-db-l2-065',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Quill',
    question: 'What is the ZIO-Quill integration and how does it differ from plain Quill?',
    options: [
      'ZIO-Quill wraps Quill contexts in ZIO effects, returning ZIO instead of plain values or Futures',
      'ZIO-Quill provides a different SQL generation strategy than plain Quill',
      'ZIO-Quill only works with ZIO\'s in-memory data stores',
      'ZIO-Quill is a fork of Quill with incompatible API',
    ],
    correctAnswer: 0,
    explanation: 'ZIO-Quill integrates Quill with ZIO, wrapping database operations in ZIO effects (ZIO[Has[DataSource], Throwable, A]) for resource safety and composability.',
    tags: ['quill', 'zio', 'integration'],
  },
  {
    id: 'scala-db-l2-066',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'What does Slick\'s `andThen` operator do on DBIO actions?',
    options: [
      'Sequences two DBIO actions, discarding the result of the first and returning the result of the second',
      'Runs two DBIO actions in parallel and combines results',
      'Creates a fallback action if the first fails',
      'Applies a function to the result of the first action',
    ],
    correctAnswer: 0,
    explanation: '`andThen` (also `>>` in cats-like notation) sequences two DBIO actions, running the first and then the second, returning only the second\'s result.',
    codeSnippet: `val action = (users += newUser) andThen users.length.result`,
    tags: ['slick', 'dbio', 'andThen', 'sequencing'],
  },
  {
    id: 'scala-db-l2-067',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'JDBC interop',
    question: 'What is the role of `java.sql.Types` constants in JDBC?',
    options: [
      'They identify SQL data types (INTEGER, VARCHAR, DATE, etc.) for use with PreparedStatement parameter types and ResultSet metadata',
      'They define connection pool configuration parameters',
      'They are used to specify the character encoding for SQL strings',
      'They configure transaction isolation levels',
    ],
    correctAnswer: 0,
    explanation: '`java.sql.Types` provides integer constants for SQL type identifiers used when registering OUT parameters for CallableStatements and when working with ResultSet metadata.',
    tags: ['jdbc', 'types', 'sql-types'],
  },
  {
    id: 'scala-db-l2-068',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'streaming queries',
    question: 'In Skunk, how do you perform cursor-based pagination?',
    options: [
      'Using session.prepare(query) and pq.cursor(params) to obtain a Cursor resource',
      'Using pq.stream(params, chunkSize) and .take(n).drop(offset)',
      'Using OFFSET/LIMIT in the SQL with lifted parameters',
      'Skunk does not support cursor-based pagination',
    ],
    correctAnswer: 0,
    explanation: 'Skunk provides cursor access via `pq.cursor(params)` which returns a `Resource[IO, Cursor[IO, A]]`. The cursor can fetch rows in controlled chunks.',
    tags: ['skunk', 'cursor', 'pagination', 'streaming'],
  },
  {
    id: 'scala-db-l2-069',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Doobie',
    question: 'How do you write a Doobie query that accepts a tuple of parameters?',
    options: [
      'Using Write[(A, B)] to encode a tuple, with fr"... = $a AND ... = $b"',
      'Using sql"... = ${(a, b)}"',
      'Using SqlTuple.from(a, b)',
      'Tuples cannot be used as query parameters in Doobie',
    ],
    correctAnswer: 0,
    explanation: 'Doobie\'s Write typeclass supports tuples. Each element of the tuple corresponds to a JDBC parameter. You can pass tuples directly in fr interpolators.',
    codeSnippet: `val name = "Alice"
val age  = 30
val q = sql"SELECT * FROM users WHERE name = $name AND age = $age".query[User].to[List]`,
    tags: ['doobie', 'parameters', 'tuple'],
  },
  {
    id: 'scala-db-l2-070',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'In Slick, what does `schema.createIfNotExists` do compared to `schema.create`?',
    options: [
      'createIfNotExists generates CREATE TABLE IF NOT EXISTS SQL; create generates CREATE TABLE which fails if the table exists',
      'createIfNotExists checks existing columns and adds missing ones; create always rebuilds the table',
      'Both generate the same SQL; they differ only in error handling',
      'createIfNotExists is not available in Slick',
    ],
    correctAnswer: 0,
    explanation: '`schema.createIfNotExists` generates IF NOT EXISTS DDL, making it idempotent. `schema.create` fails with an error if the table already exists.',
    codeSnippet: `// Safe for repeated execution:
val action = users.schema.createIfNotExists
db.run(action)`,
    tags: ['slick', 'schema', 'create-if-not-exists'],
  },
  {
    id: 'scala-db-l2-071',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'JSON codecs for DB',
    question: 'How do you use circe\'s `Encoder` and `Decoder` with Doobie for JSONB columns?',
    options: [
      'The doobie-postgres-circe module derives Meta[A] from circe Encoder/Decoder[A] implicitly',
      'You need to manually convert to/from String using encode/decode',
      'circe codecs are incompatible with Doobie; use play-json instead',
      'You must implement Doobie\'s JsonCodec[A] separately from circe codecs',
    ],
    correctAnswer: 0,
    explanation: 'The doobie-postgres-circe integration automatically creates Meta[A] instances from circe\'s implicit Encoder[A] and Decoder[A], enabling transparent JSONB column mapping.',
    codeSnippet: `import doobie.postgres.circe.jsonb.implicits._
import io.circe.generic.auto._

case class Profile(bio: String, tags: List[String])

// Profile is now a valid column type in Doobie queries
val q = sql"SELECT profile FROM users WHERE id = $id".query[Profile].option`,
    tags: ['doobie', 'circe', 'jsonb', 'meta'],
  },
  {
    id: 'scala-db-l2-072',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Skunk',
    question: 'How do you handle PostgreSQL arrays in Skunk?',
    options: [
      'Using the _text, _int4, etc. array codecs from skunk.data.Arr',
      'Using List[String] directly as a Codec',
      'Using ArrayCodec.of(varchar)',
      'PostgreSQL arrays are not supported in Skunk',
    ],
    correctAnswer: 0,
    explanation: 'Skunk provides array codecs like `_varchar`, `_int4` etc. using PostgreSQL\'s array type naming convention. Alternatively, `varchar.list(n)` creates an array codec.',
    tags: ['skunk', 'arrays', 'postgresql', 'codec'],
  },
  {
    id: 'scala-db-l2-073',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Quill',
    question: 'In Quill, how do you define a custom encoder for a type not natively supported?',
    options: [
      'By providing an implicit MappedEncoding[CustomType, BaseType]',
      'By implementing the QuillEncoder[CustomType] trait',
      'By registering with QuillContext.registerType()',
      'By annotating the field with @QuillEncode',
    ],
    correctAnswer: 0,
    explanation: 'Quill\'s `MappedEncoding[From, To]` provides bidirectional mapping between a custom type and a supported base type, similar to Slick\'s MappedColumnType.',
    codeSnippet: `case class UserId(value: Long) extends AnyVal

implicit val encodeUserId: MappedEncoding[UserId, Long] =
  MappedEncoding(_.value)
implicit val decodeUserId: MappedEncoding[Long, UserId] =
  MappedEncoding(UserId.apply)`,
    tags: ['quill', 'mapped-encoding', 'custom-type'],
  },
  {
    id: 'scala-db-l2-074',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'transactions',
    question: 'What is a savepoint in SQL transactions?',
    options: [
      'A named point within a transaction to which you can partially roll back',
      'A checkpoint that automatically commits work done so far',
      'A snapshot of the database state before a transaction begins',
      'A persistent marker used for incremental backups',
    ],
    correctAnswer: 0,
    explanation: 'A savepoint creates a named rollback point within a transaction. You can roll back to a savepoint without aborting the entire transaction, enabling partial rollbacks.',
    codeSnippet: `conn.setSavepoint("sp1")
// ... some operations
conn.rollback(sp1)  // only rolls back to sp1, not the whole transaction`,
    tags: ['transactions', 'savepoint', 'jdbc'],
  },
  {
    id: 'scala-db-l2-075',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'JDBC interop',
    question: 'What is the purpose of `connection.setSchema(schema)` in JDBC?',
    options: [
      'Sets the default database schema (search path) for the connection',
      'Creates a new database schema',
      'Validates the current schema against a definition',
      'Sets the XML schema for result parsing',
    ],
    correctAnswer: 0,
    explanation: '`setSchema` sets the default schema for unqualified table references on this connection, equivalent to `SET search_path TO schema` in PostgreSQL.',
    tags: ['jdbc', 'schema', 'connection'],
  },
  {
    id: 'scala-db-l2-076',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Doobie',
    question: 'How do you compose two ConnectionIO programs sequentially in Doobie?',
    options: [
      'Using for-comprehension (flatMap) to chain ConnectionIO values',
      'Using ConnectionIO.andThen(prog1, prog2)',
      'Using prog1.followedBy(prog2)',
      'Using Doobie.sequence(prog1, prog2)',
    ],
    correctAnswer: 0,
    explanation: 'ConnectionIO is a monad, so you compose programs using flatMap or for-comprehensions, exactly like composing IO programs in Cats Effect.',
    codeSnippet: `val program: ConnectionIO[(Int, List[User])] = for {
  count   <- sql"SELECT COUNT(*) FROM users".query[Int].unique
  users   <- sql"SELECT * FROM users LIMIT 10".query[User].to[List]
} yield (count, users)`,
    tags: ['doobie', 'connectionio', 'monad', 'composition'],
  },
  {
    id: 'scala-db-l2-077',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'streaming queries',
    question: 'In fs2 with Doobie, how do you write streaming results to a file?',
    options: [
      'Compose the Doobie stream with an fs2 pipe that writes to a file, then transact and compile',
      'Use doobie.fs2.StreamExport.toFile(path)',
      'Call stream.toFile(path) on the ConnectionIO stream',
      'Use Files.write from Java NIO directly inside the stream',
    ],
    correctAnswer: 0,
    explanation: 'You compose a Doobie query stream with an fs2 file writing pipe (fs2.io.file), apply .transact(xa), and compile the combined stream to execute everything.',
    codeSnippet: `import fs2.io.file._
import java.nio.file.Paths

sql"SELECT * FROM large_table"
  .query[String]
  .stream
  .transact(xa)
  .through(text.utf8.encode)
  .through(Files[IO].writeAll(Path("output.txt")))
  .compile.drain`,
    tags: ['doobie', 'fs2', 'streaming', 'file-io'],
  },
  {
    id: 'scala-db-l2-078',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'What is `enableExtensions` used for in slick-pg?',
    options: [
      'To enable PostgreSQL-specific features like arrays, JSONB, geometric types, and HStore in Slick',
      'To enable Slick code generation from an existing schema',
      'To enable distributed query execution',
      'To enable Slick migration utilities',
    ],
    correctAnswer: 0,
    explanation: 'slick-pg provides trait mixins (like PgArraySupport, PgJsonSupport) that you include in a custom PostgreSQL profile to enable PostgreSQL-specific column types and operators.',
    tags: ['slick', 'slick-pg', 'postgresql', 'extensions'],
  },
  {
    id: 'scala-db-l2-079',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'migrations',
    question: 'What does `flyway.info()` return?',
    options: [
      'Information about all migrations: their state (pending, applied, failed), version, and description',
      'The current database version number',
      'The connection pool statistics',
      'The Flyway library version',
    ],
    correctAnswer: 0,
    explanation: '`flyway.info()` returns a MigrationInfoService with details about all migrations — their state (pending, success, failed), versions, descriptions, and checksums.',
    tags: ['flyway', 'migrations', 'info'],
  },
  {
    id: 'scala-db-l2-080',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Doobie',
    question: 'In Doobie, what is the `HPS` module?',
    options: [
      'The high-level PreparedStatement module for setting JDBC parameters',
      'The HikariCP Session module for pool management',
      'A module for high-performance streaming queries',
      'A module for handling PostgreSQL-specific features',
    ],
    correctAnswer: 0,
    explanation: 'HPS (High-level PreparedStatement) is part of Doobie\'s free algebra. It provides operations for setting parameters on JDBC PreparedStatements in a functional way.',
    tags: ['doobie', 'hps', 'prepared-statement'],
  },
  {
    id: 'scala-db-l2-081',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'connection pooling',
    question: 'What is the difference between `minimumIdle` and `maximumPoolSize` in HikariCP?',
    options: [
      'minimumIdle is the floor of idle connections maintained; maximumPoolSize is the ceiling of total connections (active + idle)',
      'minimumIdle is the number of connections kept for reads; maximumPoolSize is for writes',
      'minimumIdle sets the initial pool size; maximumPoolSize prevents further growth',
      'Both settings control the same pool limit from different directions',
    ],
    correctAnswer: 0,
    explanation: 'minimumIdle keeps a floor of ready connections. maximumPoolSize caps the total. HikariCP recommends setting minimumIdle == maximumPoolSize (fixed pool size) for best performance.',
    tags: ['connection-pooling', 'hikaricp', 'pool-size'],
  },
  {
    id: 'scala-db-l2-082',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Quill',
    question: 'How do you perform aggregation in Quill (e.g., count all users)?',
    options: [
      'query[User].size inside a quote block',
      'query[User].count inside a quote block',
      'aggregate(query[User], COUNT)',
      'query[User].groupBy(_ => true).map(_._2.size)',
    ],
    correctAnswer: 0,
    explanation: 'In Quill, `.size` inside a quote block translates to SQL\'s COUNT(*). It is used inside a quote and run via ctx.run.',
    codeSnippet: `val count: Long = ctx.run(quote { query[User].size })`,
    tags: ['quill', 'aggregation', 'count'],
  },
  {
    id: 'scala-db-l2-083',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'JDBC interop',
    question: 'What is JDBC\'s `DatabaseMetaData` used for?',
    options: [
      'Querying metadata about the database: table names, column types, supported features, etc.',
      'Configuring the database connection properties',
      'Defining the schema for ORM mapping',
      'Monitoring active queries and performance statistics',
    ],
    correctAnswer: 0,
    explanation: 'DatabaseMetaData provides information about the database structure and capabilities: table names, column types, primary keys, indexes, supported SQL features, etc.',
    codeSnippet: `val meta = conn.getMetaData
val tables = meta.getTables(null, null, "%", Array("TABLE"))
while (tables.next()) println(tables.getString("TABLE_NAME"))`,
    tags: ['jdbc', 'metadata', 'introspection'],
  },
  {
    id: 'scala-db-l2-084',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Slick',
    question: 'How do you handle a `RETURNING` clause for non-PostgreSQL databases in Slick?',
    options: [
      'Use the `into` method: `(table returning table.map(_.id) into ((item, id) => item.copy(id = id)))`',
      'Use insertWithKey instead of returning',
      'Slick automatically handles RETURNING for all databases',
      'Use sqlu for raw SQL with RETURNING on supported databases only',
    ],
    correctAnswer: 0,
    explanation: '`into` is used with `returning` to map the generated key back into the inserted object, making the pattern portable across databases that handle generated keys differently.',
    codeSnippet: `val insertAction =
  (users returning users.map(_.id) into ((user, id) => user.copy(id = id))) += newUser
val inserted: Future[User] = db.run(insertAction)`,
    tags: ['slick', 'returning', 'into', 'insert'],
  },
  {
    id: 'scala-db-l2-085',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Doobie',
    question: 'In Doobie, how do you handle PostgreSQL enum types?',
    options: [
      'By creating a Meta[A] that maps the Scala type to/from a String or using pgEnumString',
      'PostgreSQL enums are automatically handled by Doobie',
      'By using EnumMeta.forValues[A]',
      'By casting to VARCHAR in all queries',
    ],
    correctAnswer: 0,
    explanation: 'For PostgreSQL enum types, you create a Meta[A] that reads/writes the enum as a String or use doobie-postgres\'s `pgEnumString` or `pgEnum` utilities.',
    codeSnippet: `import doobie.postgres.implicits._

// Define Scala enum
sealed trait Status
object Status {
  case object Active extends Status
  case object Inactive extends Status
}

implicit val metaStatus: Meta[Status] = pgEnumStringOpt("status",
  { case "active" => Status.Active; case "inactive" => Status.Inactive },
  { case Status.Active => "active"; case Status.Inactive => "inactive" }
)`,
    tags: ['doobie', 'postgresql', 'enum', 'meta'],
  },
  {
    id: 'scala-db-l2-086',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'Skunk',
    question: 'What does `Session.pooled` provide in Skunk vs `Session.single`?',
    options: [
      'Session.pooled manages a pool of connections; Session.single provides exactly one connection',
      'Session.pooled uses connection pooling with HikariCP; Session.single uses JDBC',
      'Session.pooled enables async execution; Session.single is blocking',
      'Session.pooled is for PostgreSQL clusters; Session.single is for standalone instances',
    ],
    correctAnswer: 0,
    explanation: 'Session.pooled creates a pool of PostgreSQL connections (managed by Skunk itself, not HikariCP). Session.single provides a single connection — suitable for tests or low-traffic scenarios.',
    codeSnippet: `// Pool of 10 connections:
Session.pooled[IO](
  host = "localhost",
  port = 5432,
  user = "postgres",
  database = "mydb",
  max = 10
)`,
    tags: ['skunk', 'session', 'pooled', 'connection-pool'],
  },
  {
    id: 'scala-db-l2-087',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'migrations',
    question: 'In a multi-tenant application, how can Flyway be used to manage per-tenant schemas?',
    options: [
      'Configure Flyway with a different defaultSchema per tenant and run migrate for each',
      'Flyway does not support multi-tenant migrations',
      'Use a single migration that creates all tenant schemas at once',
      'Use Flyway callbacks to dynamically create schemas',
    ],
    correctAnswer: 0,
    explanation: 'For multi-tenant setups, you create a Flyway instance per tenant with the appropriate schema configured, then run migrate for each. This applies the same migrations to all tenant schemas.',
    codeSnippet: `tenants.foreach { tenant =>
  Flyway.configure()
    .dataSource(url, user, pass)
    .defaultSchema(s"tenant_$tenant")
    .load()
    .migrate()
}`,
    tags: ['flyway', 'migrations', 'multi-tenant'],
  },
  {
    id: 'scala-db-l2-088',
    language: 'scala',
    level: 'level2',
    category: 'Database & Persistence',
    subcategory: 'streaming queries',
    question: 'What happens to a Doobie streaming query if the underlying connection is closed before the stream is consumed?',
    options: [
      'The stream will fail with a SQLException when it tries to fetch the next batch of rows',
      'The stream silently terminates with an empty result',
      'The stream automatically reconnects using the Transactor',
      'The stream caches all rows before the connection closes, so it completes normally',
    ],
    correctAnswer: 0,
    explanation: 'Doobie streams require an open connection for the duration of consumption. If the connection closes, fetching the next chunk will throw a SQLException.',
    tags: ['doobie', 'streaming', 'connection', 'error-handling'],
  },
];

export default questions;
