import { Question } from '@/types/question';

const questions: Question[] = [
  {
    "language": "english", "id": "b1-startup-p1-001",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is a 'startup'?",
    "options": [
      "Any small business with fewer than 10 employees",
      "A newly founded company designed to grow rapidly and scale",
      "A tech company that has just launched an app",
      "A sole trader registering their first business"
    ],
    "correctAnswer": 1,
    "explanation": "A startup is a young company founded to develop a scalable product or service, typically seeking rapid growth. Not all small businesses are startups — startups are defined by their growth ambition.",
    "subcategory": "startup basics",
    "tags": ["business-english", "startup", "startup-basics"]
  },
  {
    "language": "english", "id": "b1-startup-p1-002",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What does 'MVP' stand for in the startup world?",
    "options": [
      "Most Valuable Product",
      "Minimum Viable Product",
      "Market Validation Prototype",
      "Maximum Value Proposition"
    ],
    "correctAnswer": 1,
    "explanation": "An MVP (Minimum Viable Product) is the simplest version of a product with just enough features to attract early customers and validate the business idea before full development.",
    "subcategory": "MVP",
    "tags": ["business-english", "startup", "mvp"]
  },
  {
    "language": "english", "id": "b1-startup-p1-003",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is 'burn rate' in a startup context?",
    "options": [
      "The speed at which a product is manufactured",
      "The rate at which a startup spends its capital before generating profit",
      "The number of customers lost per month",
      "The heat generated by server equipment"
    ],
    "correctAnswer": 1,
    "explanation": "Burn rate is the speed at which a startup uses up its cash reserves. A monthly burn rate of $50K means the company is spending $50,000 per month more than it earns.",
    "subcategory": "burn rate",
    "tags": ["business-english", "startup", "burn-rate", "finance"]
  },
  {
    "language": "english", "id": "b1-startup-p1-004",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is 'runway' in startup finance?",
    "options": [
      "The amount of office space available",
      "The number of months a startup can operate before running out of money",
      "The length of a company's product roadmap",
      "The path to an IPO"
    ],
    "correctAnswer": 1,
    "explanation": "Runway is the number of months a startup can continue operating at its current burn rate before it runs out of cash. A 12-month runway means the company has 12 months to become profitable or raise more funding.",
    "subcategory": "runway",
    "tags": ["business-english", "startup", "runway", "finance"]
  },
  {
    "language": "english", "id": "b1-startup-p1-005",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is 'seed funding'?",
    "options": [
      "The final round of investment before an IPO",
      "The earliest stage of external investment to develop an initial idea",
      "Government grants for agricultural businesses",
      "Funding given only to tech companies"
    ],
    "correctAnswer": 1,
    "explanation": "Seed funding is the earliest stage of external investment — typically used to develop the MVP, conduct market research, and build the founding team. It often comes from angel investors or early-stage VCs.",
    "subcategory": "fundraising",
    "tags": ["business-english", "startup", "seed-funding", "fundraising"]
  },
  {
    "language": "english", "id": "b1-startup-p1-006",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is 'Series A' funding?",
    "options": [
      "The very first funding a startup receives from friends and family",
      "The first significant round of venture capital funding after proving initial traction",
      "A type of government loan for small businesses",
      "The funding round that takes a company public"
    ],
    "correctAnswer": 1,
    "explanation": "Series A is the first significant institutional funding round, typically occurring after a startup has demonstrated market traction (e.g., revenue growth, user base). It is used to scale the business.",
    "subcategory": "fundraising",
    "tags": ["business-english", "startup", "series-a", "fundraising"]
  },
  {
    "language": "english", "id": "b1-startup-p1-007",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is an 'IPO'?",
    "options": [
      "Intellectual Property Office",
      "Initial Public Offering — when a company sells shares to the public for the first time",
      "Internal Product Optimisation",
      "Investor Partnership Obligation"
    ],
    "correctAnswer": 1,
    "explanation": "An IPO (Initial Public Offering) is when a private company first offers its shares to the public on a stock exchange. It is a major milestone that allows early investors to realise their returns.",
    "subcategory": "IPO",
    "tags": ["business-english", "startup", "ipo", "fundraising"]
  },
  {
    "language": "english", "id": "b1-startup-p1-008",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What does it mean for a startup to 'pivot'?",
    "options": [
      "To shut down the company",
      "To change the business model or direction based on market feedback",
      "To expand into a new country",
      "To hire a new CEO"
    ],
    "correctAnswer": 1,
    "explanation": "A pivot is a fundamental change in a startup's strategy, product, or business model in response to feedback or market data. Famous pivots include Slack (from gaming platform) and YouTube (from dating site).",
    "subcategory": "pivoting",
    "tags": ["business-english", "startup", "pivot"]
  },
  {
    "language": "english", "id": "b1-startup-p1-009",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is a 'cap table' (capitalisation table)?",
    "options": [
      "A table in the board meeting room",
      "A spreadsheet showing ownership percentages and equity stakes in a company",
      "A cap on the amount of investment allowed",
      "A list of company capital equipment"
    ],
    "correctAnswer": 1,
    "explanation": "A cap table (capitalisation table) shows who owns what percentage of a company, including founders, investors, and employees with equity. It is essential for understanding dilution through funding rounds.",
    "subcategory": "cap table",
    "tags": ["business-english", "startup", "cap-table", "equity"]
  },
  {
    "language": "english", "id": "b1-startup-p1-010",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is a 'term sheet' in fundraising?",
    "options": [
      "A list of payment terms for suppliers",
      "A non-binding document outlining the key terms of a proposed investment",
      "The final signed investment contract",
      "A sheet showing company expenses"
    ],
    "correctAnswer": 1,
    "explanation": "A term sheet is a non-binding agreement that outlines the key terms and conditions of a proposed investment — valuation, equity stake, investor rights — before a full legal agreement is drafted.",
    "subcategory": "term sheet",
    "tags": ["business-english", "startup", "term-sheet", "fundraising"]
  },
  {
    "language": "english", "id": "b1-startup-p1-011",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is 'equity' in a startup context?",
    "options": [
      "Equal pay for all employees",
      "Ownership stake in the company, usually expressed as a percentage",
      "A type of long-term business loan",
      "The profit distributed to shareholders"
    ],
    "correctAnswer": 1,
    "explanation": "Equity represents ownership in a company. Founders, investors, and employees with stock options all hold equity. As new investors come in, equity percentages are 'diluted'.",
    "subcategory": "equity/vesting",
    "tags": ["business-english", "startup", "equity"]
  },
  {
    "language": "english", "id": "b1-startup-p1-012",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is 'vesting' in the context of employee equity?",
    "options": [
      "The process of investing in the stock market",
      "The schedule by which employees earn their equity over time",
      "Wearing formal business attire",
      "The legal transfer of company ownership"
    ],
    "correctAnswer": 1,
    "explanation": "Vesting is the process by which employees gradually earn ownership of their equity grants over time. A 4-year vesting schedule means an employee earns their full equity allocation over 4 years.",
    "subcategory": "equity/vesting",
    "tags": ["business-english", "startup", "vesting", "equity"]
  },
  {
    "language": "english", "id": "b1-startup-p1-013",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is a 'cliff' in a vesting schedule?",
    "options": [
      "A sudden drop in company valuation",
      "The initial period before any equity vests (e.g., 1 year before any shares are earned)",
      "A cap on the maximum equity any employee can hold",
      "The point when an employee's equity expires"
    ],
    "correctAnswer": 1,
    "explanation": "A vesting cliff is the minimum time an employee must stay before any equity vests at all. A 1-year cliff means if an employee leaves before one year, they receive nothing; at one year, they receive the first tranche.",
    "subcategory": "equity/vesting",
    "tags": ["business-english", "startup", "vesting-cliff", "equity"]
  },
  {
    "language": "english", "id": "b1-startup-p1-014",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is 'product-market fit'?",
    "options": [
      "Ensuring a product meets manufacturing specifications",
      "The degree to which a product satisfies strong market demand",
      "Matching a product to its physical retail location",
      "The process of designing packaging for a new product"
    ],
    "correctAnswer": 1,
    "explanation": "Product-market fit means a startup's product genuinely satisfies the needs of a market segment. Marc Andreessen defined it as being in a good market with a product that satisfies that market.",
    "subcategory": "product-market fit",
    "tags": ["business-english", "startup", "product-market-fit"]
  },
  {
    "language": "english", "id": "b1-startup-p1-015",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What does 'traction' mean when a startup says it has 'strong traction'?",
    "options": [
      "The company has good tyres on its delivery vehicles",
      "Measurable evidence of customer adoption and growth",
      "The CEO has a strong business network",
      "The startup has filed its patents"
    ],
    "correctAnswer": 1,
    "explanation": "Traction refers to measurable signs that a startup is gaining momentum — user growth, revenue, engagement, or retention. Investors look for traction as proof of product-market fit.",
    "subcategory": "startup metrics",
    "tags": ["business-english", "startup", "traction"]
  },
  {
    "language": "english", "id": "b1-startup-p1-016",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is 'growth hacking'?",
    "options": [
      "Illegally accessing competitors' growth data",
      "Using creative, low-cost strategies focused on rapid user growth",
      "A technique for growing a vegetable garden efficiently",
      "A method of increasing employee salaries"
    ],
    "correctAnswer": 1,
    "explanation": "Growth hacking is a marketing approach that uses rapid experimentation, data, and creative tactics to grow a user base quickly and cheaply. Famous examples include Dropbox's referral programme and Airbnb's Craigslist integration.",
    "subcategory": "growth hacking",
    "tags": ["business-english", "startup", "growth-hacking"]
  },
  {
    "language": "english", "id": "b1-startup-p1-017",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What does 'iterate fast' mean in startup culture?",
    "options": [
      "Hire as quickly as possible",
      "Build, test, learn, and improve quickly through rapid product cycles",
      "Repeat the same marketing campaign multiple times",
      "Automate all repetitive tasks"
    ],
    "correctAnswer": 1,
    "explanation": "'Iterate fast' is a core lean startup principle: build a version, get user feedback, learn from it, and quickly release an improved version. Speed of learning is a competitive advantage.",
    "subcategory": "iterate fast",
    "tags": ["business-english", "startup", "iteration", "lean-startup"]
  },
  {
    "language": "english", "id": "b1-startup-p1-018",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is 'due diligence' in the context of startup investment?",
    "options": [
      "Paying invoices on time",
      "An investor's thorough investigation of a startup before committing money",
      "A startup's research into its competitors",
      "The process of registering a company legally"
    ],
    "correctAnswer": 1,
    "explanation": "Due diligence is the comprehensive review an investor or acquirer performs before investing or buying a company — examining financials, legal status, team, technology, and market opportunity.",
    "subcategory": "due diligence",
    "tags": ["business-english", "startup", "due-diligence", "fundraising"]
  },
  {
    "language": "english", "id": "b1-startup-p1-019",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is 'valuation' in startup fundraising?",
    "options": [
      "The book value of company assets",
      "The estimated worth of a company at a given point in time",
      "The salary valuation of the founding team",
      "The value of the startup's intellectual property only"
    ],
    "correctAnswer": 1,
    "explanation": "Valuation is the estimated total worth of a startup. In fundraising, it determines how much equity an investor gets for their money. A $10M investment at a $100M valuation buys 10% of the company.",
    "subcategory": "valuation",
    "tags": ["business-english", "startup", "valuation", "fundraising"]
  },
  {
    "language": "english", "id": "b1-startup-p1-020",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is a 'VC' in the startup ecosystem?",
    "options": [
      "Vice Chairman",
      "Venture Capitalist — a professional investor who funds startups in exchange for equity",
      "Virtual Company",
      "Value Creator"
    ],
    "correctAnswer": 1,
    "explanation": "A Venture Capitalist (VC) is an investor or firm that provides capital to startups with high growth potential in exchange for equity. VC firms manage funds from institutional investors (LPs).",
    "subcategory": "venture capital",
    "tags": ["business-english", "startup", "venture-capital", "vc"]
  },
  {
    "language": "english", "id": "b1-startup-p1-021",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is an 'angel investor'?",
    "options": [
      "An investor who only funds non-profit organisations",
      "A high-net-worth individual who invests their own money in early-stage startups",
      "A government-backed investor for social enterprises",
      "A crowdfunding platform participant"
    ],
    "correctAnswer": 1,
    "explanation": "Angel investors are wealthy individuals who invest their personal funds in early-stage startups, often before VC involvement. They provide capital, mentorship, and network access in exchange for equity.",
    "subcategory": "angel investor",
    "tags": ["business-english", "startup", "angel-investor", "fundraising"]
  },
  {
    "language": "english", "id": "b1-startup-p1-022",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is a 'pivot' in startup terminology?",
    "options": [
      "A sudden change in the company's leadership team",
      "A fundamental shift in the startup's strategy, product, or target market after learning from initial results",
      "A minor feature update released in the first sprint",
      "Moving the startup's physical office to a new location"
    ],
    "correctAnswer": 1,
    "explanation": "A pivot is a structured course correction — a significant change in product, business model, or market based on validated learning. Famous pivots include Instagram (from a check-in app) and Slack (from a gaming company).",
    "subcategory": "startup basics",
    "tags": ["business-english", "startup", "pivot", "lean-startup"]
  },
  {
    "language": "english", "id": "b1-startup-p1-023",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is a 'board meeting' in a startup context?",
    "options": [
      "A meeting held in a room with a whiteboard",
      "A formal meeting of the board of directors to oversee company direction and governance",
      "A weekly all-hands staff meeting",
      "A meeting with the founding team only"
    ],
    "correctAnswer": 1,
    "explanation": "Board meetings bring together the board of directors (founders, investors, and independent directors) to review performance, approve major decisions, and provide governance oversight. Typically held quarterly.",
    "subcategory": "board meetings",
    "tags": ["business-english", "startup", "board-meetings"]
  },
  {
    "language": "english", "id": "b1-startup-p1-024",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What does 'dilution' mean for startup founders?",
    "options": [
      "When a product's quality decreases over time",
      "When a founder's ownership percentage decreases as new shares are issued to investors",
      "When a startup's market shrinks",
      "When the company's products are discounted"
    ],
    "correctAnswer": 1,
    "explanation": "Dilution occurs when new shares are issued (e.g., in a funding round), reducing existing shareholders' percentage ownership. A founder owning 80% before a new round may own 60% after it.",
    "subcategory": "equity/dilution",
    "tags": ["business-english", "startup", "dilution", "equity"]
  },
  {
    "language": "english", "id": "b1-startup-p1-025",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is 'bootstrapping' a startup?",
    "options": [
      "Raising venture capital as quickly as possible",
      "Building a company using personal savings and revenue without external investment",
      "Starting a fashion technology company",
      "Copying another company's business model"
    ],
    "correctAnswer": 1,
    "explanation": "Bootstrapping means building a startup using personal funds and revenue generated by the business, without external investors. Bootstrapped founders retain full equity but have limited capital for growth.",
    "subcategory": "bootstrapping",
    "tags": ["business-english", "startup", "bootstrapping"]
  },
  {
    "language": "english", "id": "b1-startup-p1-026",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is 'churn' in a SaaS (Software as a Service) startup?",
    "options": [
      "The process of producing dairy products",
      "The percentage of customers who cancel their subscription in a given period",
      "The speed of product development",
      "Employee turnover rate"
    ],
    "correctAnswer": 1,
    "explanation": "Churn rate is the percentage of subscribers who cancel or do not renew their subscriptions. High churn signals poor product-market fit or customer satisfaction issues. Reducing churn is critical for SaaS growth.",
    "subcategory": "startup metrics",
    "tags": ["business-english", "startup", "churn", "saas"]
  },
  {
    "language": "english", "id": "b1-startup-p1-027",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What does 'go-to-market' (GTM) strategy mean?",
    "options": [
      "A plan for how a company will physically go to a market to sell",
      "The strategy for launching a product and reaching target customers",
      "A logistics plan for supply chain management",
      "The process of listing a company on a stock exchange"
    ],
    "correctAnswer": 1,
    "explanation": "A go-to-market strategy is the plan a company uses to deliver its product to the right customers through the right channels. It includes target market, pricing, distribution, and marketing approach.",
    "subcategory": "go-to-market",
    "tags": ["business-english", "startup", "go-to-market", "strategy"]
  },
  {
    "language": "english", "id": "b1-startup-p1-028",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is a 'unicorn' company?",
    "options": [
      "A startup that specialises in mythological content",
      "A privately held startup valued at over $1 billion",
      "A company that has never made a profit",
      "A startup with only one co-founder"
    ],
    "correctAnswer": 1,
    "explanation": "A 'unicorn' is a privately held startup valued at $1 billion or more. The term was coined by Aileen Lee in 2013 to describe how rare such companies once were. Examples: Stripe, Canva, SpaceX before their IPOs.",
    "subcategory": "startup milestones",
    "tags": ["business-english", "startup", "unicorn", "valuation"]
  },
  {
    "language": "english", "id": "b1-startup-p1-029",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What does 'ARR' stand for in SaaS businesses?",
    "options": [
      "Annual Recurring Revenue",
      "Asset Return Rate",
      "Account Receivable Ratio",
      "Average Revenue Rate"
    ],
    "correctAnswer": 0,
    "explanation": "ARR (Annual Recurring Revenue) is the predictable revenue a SaaS company expects to generate annually from subscriptions. It is a key metric investors use to value SaaS startups.",
    "subcategory": "startup metrics",
    "tags": ["business-english", "startup", "arr", "saas", "metrics"]
  },
  {
    "language": "english", "id": "b1-startup-p1-030",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is 'MRR' in a subscription business?",
    "options": [
      "Marketing Revenue Report",
      "Monthly Recurring Revenue",
      "Management Resource Ratio",
      "Market Research Result"
    ],
    "correctAnswer": 1,
    "explanation": "MRR (Monthly Recurring Revenue) is the total predictable monthly revenue from subscriptions. Growing MRR is a key health indicator for SaaS and subscription businesses.",
    "subcategory": "startup metrics",
    "tags": ["business-english", "startup", "mrr", "saas"]
  },
  {
    "language": "english", "id": "b1-startup-p1-031",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is a 'convertible note' in startup fundraising?",
    "options": [
      "A bank note that can be exchanged for foreign currency",
      "A short-term debt instrument that converts into equity at a future funding round",
      "A document converting a company from LLC to Corp",
      "A note explaining why a startup changed its business model"
    ],
    "correctAnswer": 1,
    "explanation": "A convertible note is a loan that 'converts' into equity at the next qualifying funding round, usually at a discount. It allows early investors to get in before a valuation is set.",
    "subcategory": "fundraising",
    "tags": ["business-english", "startup", "convertible-note", "fundraising"]
  },
  {
    "language": "english", "id": "b1-startup-p1-032",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is 'pre-money valuation'?",
    "options": [
      "The valuation of a company before any revenue is generated",
      "A company's estimated value before a new investment round",
      "The value of a startup's pre-launch products",
      "The assessment of a company's market potential"
    ],
    "correctAnswer": 1,
    "explanation": "Pre-money valuation is the value of a startup before new investment is added. Post-money valuation = pre-money valuation + new investment. These terms are critical in negotiating funding rounds.",
    "subcategory": "valuation",
    "tags": ["business-english", "startup", "pre-money-valuation", "fundraising"]
  },
  {
    "language": "english", "id": "b1-startup-p1-033",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What does 'customer acquisition cost' (CAC) measure?",
    "options": [
      "How much it costs to manufacture a product",
      "The total cost of acquiring a new customer",
      "The cost of retaining existing customers",
      "The price a customer pays for a product"
    ],
    "correctAnswer": 1,
    "explanation": "CAC is the total cost of sales and marketing efforts to acquire one new customer. A sustainable business must earn more from a customer (LTV) than it costs to acquire them (CAC).",
    "subcategory": "startup metrics",
    "tags": ["business-english", "startup", "cac", "metrics"]
  },
  {
    "language": "english", "id": "b1-startup-p1-034",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is 'LTV' (Lifetime Value)?",
    "options": [
      "Long-Term Vision of a startup",
      "The total revenue expected from a customer over their entire relationship with the company",
      "A live television advertising metric",
      "The last transaction value of a customer"
    ],
    "correctAnswer": 1,
    "explanation": "LTV (or CLV — Customer Lifetime Value) is the total revenue a business expects to earn from a single customer account. A healthy business typically has an LTV significantly higher than its CAC.",
    "subcategory": "startup metrics",
    "tags": ["business-english", "startup", "ltv", "metrics"]
  },
  {
    "language": "english", "id": "b1-startup-p1-035",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is an 'accelerator' in the startup world?",
    "options": [
      "A computer component that speeds up processing",
      "A programme that provides mentorship, resources, and funding to early-stage startups",
      "An investor who moves quickly to close deals",
      "A tool for accelerating website loading speeds"
    ],
    "correctAnswer": 1,
    "explanation": "A startup accelerator (e.g., Y Combinator, Techstars) is a fixed-term programme offering mentorship, workspace, networking, and usually a small investment in exchange for equity, culminating in a 'Demo Day'.",
    "subcategory": "startup ecosystem",
    "tags": ["business-english", "startup", "accelerator"]
  },
  {
    "language": "english", "id": "b1-startup-p1-036",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is a 'demo day' in the accelerator programme context?",
    "options": [
      "A day when startups demonstrate their products to the public for free",
      "A final event where startups pitch to a room of investors",
      "A technical demonstration for internal team review",
      "A day for testing new software before release"
    ],
    "correctAnswer": 1,
    "explanation": "Demo Day is the culminating event of an accelerator programme where startups pitch their companies to a large audience of investors. Y Combinator's Demo Day is one of the most competitive investor events in the world.",
    "subcategory": "startup ecosystem",
    "tags": ["business-english", "startup", "demo-day", "accelerator"]
  },
  {
    "language": "english", "id": "b1-startup-p1-037",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What does 'freemium' mean as a business model?",
    "options": [
      "Offering all products completely free",
      "Offering a basic service free, with premium features available for a fee",
      "Giving away a product for free to first-time customers only",
      "A model where customers pay as they grow"
    ],
    "correctAnswer": 1,
    "explanation": "Freemium (free + premium) offers a basic version free to attract users, then charges for advanced features. Examples: Spotify, Zoom, Slack. The goal is to convert free users into paying customers.",
    "subcategory": "business models",
    "tags": ["business-english", "startup", "freemium", "business-model"]
  },
  {
    "language": "english", "id": "b1-startup-p1-038",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is the 'lean startup' methodology?",
    "options": [
      "Running a startup with minimal staff",
      "Build-Measure-Learn cycle: rapidly testing assumptions and iterating based on feedback",
      "A startup that only makes physical products",
      "A startup with very low costs"
    ],
    "correctAnswer": 1,
    "explanation": "The Lean Startup (Eric Ries) methodology advocates building an MVP, measuring its performance, and learning from the data to either iterate or pivot. The goal is to reduce waste by validating assumptions early.",
    "subcategory": "lean startup",
    "tags": ["business-english", "startup", "lean-startup"]
  },
  {
    "language": "english", "id": "b1-startup-p1-039",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is 'Series B' funding?",
    "options": [
      "The second stage of venture funding, used to scale a proven business model",
      "The first institutional funding round",
      "Funding received from a second investor only",
      "A government grant for scale-ups"
    ],
    "correctAnswer": 0,
    "explanation": "Series B is the second major VC funding round, typically raised after Series A when the startup has demonstrated product-market fit. It is used to scale operations, expand to new markets, and grow the team.",
    "subcategory": "fundraising",
    "tags": ["business-english", "startup", "series-b", "fundraising"]
  },
  {
    "language": "english", "id": "b1-startup-p1-040",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is a 'liquidation preference' in a startup investment?",
    "options": [
      "A preference to shut down the company quickly",
      "The right of investors to be paid before founders in a sale or liquidation event",
      "A preference for liquid assets over physical assets",
      "The order in which bank loans are repaid"
    ],
    "correctAnswer": 1,
    "explanation": "Liquidation preference is a legal term in term sheets giving investors the right to receive their investment back before founders and common shareholders in the event of a sale, merger, or liquidation.",
    "subcategory": "term sheet",
    "tags": ["business-english", "startup", "liquidation-preference", "fundraising"]
  },
  {
    "language": "english", "id": "b1-startup-p1-041",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is 'SAFE' (Simple Agreement for Future Equity)?",
    "options": [
      "An insurance product for startups",
      "An investment instrument that gives rights to future equity without setting an immediate valuation",
      "A safety protocol for startup offices",
      "A software security framework"
    ],
    "correctAnswer": 1,
    "explanation": "A SAFE (created by Y Combinator) is a simple investment contract where an investor gives money now in exchange for the right to receive equity in a future round. It avoids the complexity of debt instruments.",
    "subcategory": "fundraising",
    "tags": ["business-english", "startup", "safe", "fundraising"]
  },
  {
    "language": "english", "id": "b1-startup-p1-042",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is a 'product roadmap' in a tech startup?",
    "options": [
      "A physical map of office locations",
      "A strategic plan showing the vision, direction, and planned development of a product over time",
      "A list of all bugs to be fixed",
      "A delivery schedule for physical products"
    ],
    "correctAnswer": 1,
    "explanation": "A product roadmap communicates the high-level plan for product development, including features, priorities, and timelines. It aligns the team and informs stakeholders about where the product is headed.",
    "subcategory": "product management",
    "tags": ["business-english", "startup", "product-roadmap"]
  },
  {
    "language": "english", "id": "b1-startup-p1-043",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is a 'go-to-market' (GTM) strategy?",
    "options": [
      "A plan for relocating the company's headquarters to a larger market",
      "A plan outlining how a company will launch a product and reach its target customers",
      "A strategy for entering stock market listings",
      "A roadmap for expanding to international markets only"
    ],
    "correctAnswer": 1,
    "explanation": "A go-to-market strategy defines how a company will bring a product to market — covering target customer segments, sales channels, pricing, and messaging. It is essential for every product launch.",
    "subcategory": "growth",
    "tags": ["business-english", "startup", "go-to-market", "strategy"]
  },
  {
    "language": "english", "id": "b1-startup-p1-044",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What does 'churn rate' measure in a subscription business?",
    "options": [
      "The speed at which the engineering team deploys new features",
      "The percentage of customers who cancel or stop using a service in a given period",
      "The rate at which a startup acquires new customers",
      "The amount of revenue generated per customer"
    ],
    "correctAnswer": 1,
    "explanation": "Churn rate measures how quickly a startup is losing customers. A high churn rate signals poor retention and is one of the most critical SaaS metrics — it directly determines whether growth is sustainable.",
    "subcategory": "growth",
    "tags": ["business-english", "startup", "churn-rate", "saas"]
  },
  {
    "language": "english", "id": "b1-startup-p1-045",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is 'disruption' in a startup context?",
    "options": [
      "When a startup's technology causes IT failures",
      "When a startup significantly changes or displaces an established industry or market",
      "A competitor stealing a startup's customers",
      "A merger that causes operational issues"
    ],
    "correctAnswer": 1,
    "explanation": "'Disruption' (from Clayton Christensen's theory) describes how an innovation starts by serving overlooked markets and eventually displaces established competitors. Uber disrupted taxis; Airbnb disrupted hotels.",
    "subcategory": "disruption",
    "tags": ["business-english", "startup", "disruption"]
  },
  {
    "language": "english", "id": "b1-startup-p1-046",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is a 'term sheet' in startup fundraising?",
    "options": [
      "A glossary of investor terminology",
      "A non-binding document outlining the key terms and conditions of a proposed investment",
      "The final legally signed investment contract",
      "A spreadsheet tracking quarterly financial terms"
    ],
    "correctAnswer": 1,
    "explanation": "A term sheet is typically the first formal document in a fundraising round. It outlines the key deal terms — valuation, ownership stake, board seats — before lawyers draft the final agreements.",
    "subcategory": "fundraising",
    "tags": ["business-english", "startup", "term-sheet", "fundraising"]
  },
  {
    "language": "english", "id": "b1-startup-p1-047",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is 'user retention' as a startup metric?",
    "options": [
      "The ability to remember users' names",
      "The percentage of users who continue using the product over time",
      "The number of new users acquired each month",
      "The legal ability to hold user data"
    ],
    "correctAnswer": 1,
    "explanation": "User retention measures how many customers continue using a product after their first interaction. High retention indicates product value and loyalty. It is often measured as 30-day, 60-day, or 90-day retention.",
    "subcategory": "startup metrics",
    "tags": ["business-english", "startup", "retention", "metrics"]
  },
  {
    "language": "english", "id": "b1-startup-p1-048",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is 'NPS' (Net Promoter Score)?",
    "options": [
      "Net Product Sales",
      "A measure of customer loyalty based on how likely customers are to recommend the product",
      "Number of Product Subscriptions",
      "New Profit Share"
    ],
    "correctAnswer": 1,
    "explanation": "NPS measures customer loyalty by asking: 'How likely are you to recommend us to a friend or colleague?' (0-10 scale). It is widely used in SaaS and consumer companies to gauge customer satisfaction.",
    "subcategory": "startup metrics",
    "tags": ["business-english", "startup", "nps", "metrics"]
  },
  {
    "language": "english", "id": "b1-startup-p1-049",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What does 'scale' mean when a startup says it is 'ready to scale'?",
    "options": [
      "The startup is ready to measure its products",
      "The startup is ready to grow rapidly without a proportional increase in costs",
      "The startup is ready to reduce its team size",
      "The startup is ready to enter a partnership"
    ],
    "correctAnswer": 1,
    "explanation": "Scaling means growing revenue and customer base rapidly while keeping cost growth relatively flat. A business is 'scalable' if adding more customers doesn't require a proportional increase in costs.",
    "subcategory": "scaling",
    "tags": ["business-english", "startup", "scaling"]
  },
  {
    "language": "english", "id": "b1-startup-p1-050",
    "level": "b1",
    "category": "Startup & Tech Business",
    "question": "What is 'market size' in a startup pitch?",
    "options": [
      "The physical size of a market or trade show",
      "The total potential revenue opportunity in a startup's target market",
      "The number of competitors in a market",
      "The number of physical stores in a sector"
    ],
    "correctAnswer": 1,
    "explanation": "Market size (often expressed as TAM/SAM/SOM) tells investors how large the opportunity is. A large addressable market signals significant growth potential — a key factor in investment decisions.",
    "subcategory": "investor pitch",
    "tags": ["business-english", "startup", "market-size", "pitch"]
  }
];

export default questions;
